### ISSUE TITLE
New icon: Xing

### ISSUE THREAD

**Issue by rbnis** [feathericons/feather#1023]
## Icon Request

* Icon name: xing
* Use case: Similar to "linkedin".
* Screenshots of similar icons:
  * Original: ![image](https://user-images.githubusercontent.com/5955614/103587447-8fafb100-4ee7-11eb-9699-c6cf8750f3ea.png)
  * SVG: ![SVG](https://user-images.githubusercontent.com/5955614/103586896-5e82b100-4ee6-11eb-9a3f-e58142f03076.png)

* SVG: [xing.svg.zip](https://github.com/feathericons/feather/files/5767122/xing.svg.zip)

**Comment by locness3** [comment]
Hi! Brand icons are not accepted anymore, see #763

**Comment by rbnis** [comment]
Ahh, okay. Kinda understandable. I'll just use it locally then. But thanks for having a look :)
