### ISSUE TITLE
Feather Icons website isn't working

### ISSUE THREAD

**Issue by itsag** [feathericons/feather#1031]
Not sure if this is the right place to notify about this.

https://feathericons.com isn't working. Browser says the address is unreachable.

**Comment by locness3** [comment]
Up for me. But maybe it's progressively dying? I hope not

**Comment by itsag** [comment]
It's been around 12 hours and still not working.

**Comment by uiuxarghya** [comment]
It's up for me. Hope you get it working again fast.

**Comment by itsag** [comment]
Up now
