### ISSUE TITLE
Drag icon

### ISSUE THREAD

**Issue by jvidalv** [feathericons/feather#1052]
## Icon Request

* Icon name: Drag
* Use case: For draggable content
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/27777508/109787744-d7646780-7c0e-11eb-9b44-8a121f1e7b18.png)

**Comment by locness3** [comment]
I'm pretty sure this was already asked

**Comment by ericfennis** [comment]
Yes by me in #888
