### ISSUE TITLE
Discord Icon

### ISSUE THREAD

**Issue by VinceTheGenius** [feathericons/feather#1156]
## Icon Request

* Icon name: Discord
* Use case: Social
* Screenshots of similar icons: Come on !

After 5 years, since the first issue, WHERE IS THE F*CKG DISCORD ICON ? 😂😂

Please add it !

Thanks for all icons !

Have a nice day :)

**Comment by karsa-mistmere** [comment]
@VinceTheGenius Please refrain from [any profanity](https://github.com/feathericons/feather/blob/master/CODE_OF_CONDUCT.md).

Brand icons are deprecated as stated in #763, and Feather does not seem to have accepted any new icons in more than two years anyway.

I suggest that you go with https://github.com/simple-icons/simple-icons/blob/develop/icons/discord.svg from [simple-icons](https://github.com/simple-icons/simple-icons), as recommended by both Feather and [Lucide](https://lucide.dev/).

If you really really _really_ need a Feather style Discord icon feel free to use this for your own needs, but be aware that this does in fact go against [Discord's brand guidelines](https://discord.com/branding):
```
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="m8 17-.55 2C5.5 18.5 3.5 17.5 2 16.27 2 11 3.5 7.5 5 5c0 0 2.5-1 4.5-1l.5 1.36a4.82 4.82 0 0 1 4 .14l.5-1.5c2 0 4.5 1 4.5 1 1.5 2.5 3 6 3 11.27A14.68 14.68 0 0 1 16.55 19L16 17" />
  <path d="M7.5 16.5c.73.5 2 1.5 4.5 1.5s3.77-1 4.5-1.5" />
  <circle cx="9" cy="12" r="1" />
  <circle cx="15" cy="12" r="1" />
</svg>
```

**Comment by lucasm** [comment]
Please make this happen

**Comment by locness3** [comment]
> Please make this happen

It will not, please read @karsa-mistmere 's comment above.
