### ISSUE TITLE
Can I request a Black solid TruthSocial icon?

### ISSUE THREAD

**Issue by ghost** [feathericons/feather#1157]
## Icon Request

* Icon name: TruthSocial
* Use case: Ghost.org Footer
* Screenshots of similar icons: https://1000logos.net/wp-content/uploads/2022/05/Truth-Social-Emblem.png

**Comment by karsa-mistmere** [comment]
Brand icons are [deprecated](https://github.com/feathericons/feather/issues/763), no new brand icons will be added.
