### ISSUE TITLE
TicTok?

### ISSUE THREAD

**Issue by jamiegalbreath** [feathericons/feather#1166]
## Icon Request

* Icon name:
* Use case:
* Screenshots of similar icons:

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated: https://github.com/feathericons/feather/issues/763

Please use simpleicons.org

**Comment by tryoxiss** [comment]
Brand icons are [depreciated](https://github.com/feathericons/feather/issues/763). Please use [simpleicons.org](https://simpleicons.org/) instead.
