### ISSUE TITLE
Discord icon

### ISSUE THREAD

**Issue by abdoachhoubi** [feathericons/feather#1189]
## Icon Request

* Icon name: Discord
* Use case: Social Icon
* Screenshots of similar icons:
![636e0a6a49cf127bf92de1e2_icon_clyde_blurple_RGB](https://user-images.githubusercontent.com/78739445/208890216-427a5dd6-874c-4cb6-a48f-bb1094950cbe.png)

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated and Discord has already been requested a zillion times.
#1156 #955 #30 #763 

Use simpleicons.
