### ISSUE TITLE
Icon request: Biolink

### ISSUE THREAD

**Issue by StephenCavender** [feathericons/feather#1193]
An icon for [Biolink](https://bio.link/).
Here's a version I grabbed from their site and modified to use on [my site](https://dev.cavender.io/): 

![biolink](https://user-images.githubusercontent.com/6619472/212398869-6f637b96-db79-44ab-a5aa-17201c4336f2.svg)
(hard to see in dark mode)

[Attachment](https://user-images.githubusercontent.com/6619472/212398869-6f637b96-db79-44ab-a5aa-17201c4336f2.svg)

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated: #763
