### ISSUE TITLE
Google Scholar

### ISSUE THREAD

**Issue by willshiao** [feathericons/feather#1194]
## Icon Request

* Icon name: Google Scholar
* Use case: For people that want to represent Google Scholar with an icon.
* Screenshots of similar icons: [official Google Scholar SVG](https://commons.wikimedia.org/wiki/File:Google_Scholar_logo.svg)

**Comment by karsa-mistmere** [comment]
[Brand icons are deprecated](#763) and the Google Scholar logo is protected by trademark to begin with.
