### ISSUE TITLE
Tumblr

### ISSUE THREAD

**Issue by suatkaygisiz** [feathericons/feather#1198]
## Icon Request

* Icon name: Tumblr
* Use case: Web
* Screenshots of similar icons:  
![resim_2023-04-13_165452933](https://user-images.githubusercontent.com/17141547/231781060-88c62cde-8e78-4c67-ac09-4bafcd541162.png)

**Comment by karsa-mistmere** [comment]
Brand icons are deprecated: https://github.com/feathericons/feather/issues/763
