### ISSUE TITLE
Icon request: power-off

### ISSUE THREAD

**Issue by d4rky-pl** [feathericons/feather#1222]
### Icon name

power-off

### Use case

There's a power icon already, would be great to have the equivalent of other -off icons

### Screenshots of similar icons

I'd say something like this:

![power-off](https://github.com/feathericons/feather/assets/284395/a935f7e2-f53e-4272-8a9f-fb0ba2827ca6)

but I'm not a designer so it may require tweaking

### Checklist

- [X] I have searched the existing icons to make sure this icon does not already exist.
- [X] I have searched the existing issues to make sure this icon has not already been requested.
- [X] This icon is not a logo.

**Comment by shooka** [comment]
Hey @d4rky-pl.

Just came by your issue as I was looking for a specific issue myself.

While I get what you're going at, the icon you suggest doesn't make sense as the power icon is already a _switch_. On and off are both represented in the icon already as I being on and O being off (also 1 and 0). See the [wikipedia page](https://en.wikipedia.org/wiki/Power_symbol) for further explanation on the standard.

Maybe you could use color or in some other way let your users know of the current state of whatever it is they're trying to turn on/off (like a TV, where the owner will know what the power button on the remote does when pressed based on if the TV is currently on or off).

Hope this helps.

**Comment by d4rky-pl** [comment]
@shooka thanks for your reply. I just switched to [Lucide](https://lucide.dev/icons/power-off) instead.

**Comment by shooka** [comment]
@d4rky-pl My goal wasn't to make you close your issue. I am not one of the maintainers, I am a user like you. My comment was to let you know that the icon is a bit confusing. You should of course try your luck with the feather designers, if you still want the icon.

**Comment by d4rky-pl** [comment]
@shooka no, it's fine and I know you're not one of the maintainers, it's that since I've created the issue I've realised that this repository is not actively maintained and the library stopped growing. I just forgot to close the issue until now
