### ISSUE TITLE
Icon request: Wechat

### ISSUE THREAD

**Issue by jiekun** [feathericons/feather#1232]
### Icon name

wechat

### Use case

WeChat is a social media/chat app, widely used in many areas.

https://www.wechat.com/en/

### Screenshots of similar icons

A PNG icon could be found here:
![image](https://github.com/feathericons/feather/assets/30280396/c27322fb-c1e2-4670-afed-bf69b5106499)

![image](https://github.com/feathericons/feather/assets/30280396/68d55dd7-2cec-45fc-8514-b026bf5700d0)

And a lot of SVG icon could be cound here:
https://www.iconfont.cn/search/index?searchType=icon&q=wechat

However, most of them do not fit **feather**. So I would like to make a request here.

### Checklist

- [X] I have searched the existing icons to make sure this icon does not already exist.
- [X] I have searched the existing issues to make sure this icon has not already been requested.
- [X] This icon is not a logo.

**Comment by MarcelloTheArcane** [comment]
You have ticked that this icon is not a logo - but it is a logo.

Brand icons are deprecated:  #763
