### ISSUE TITLE
Icon request: rss

### ISSUE THREAD

**Issue by alexantr** [feathericons/feather#13]
Icon name: rss
For rss feeds
Example:

![rss](https://cloud.githubusercontent.com/assets/4941848/26624493/b6358ab6-45f9-11e7-8a83-4ed5201503c0.png)

**Comment by chetanraj** [comment]
+1

**Comment by drewish** [comment]
Worth cross linking to #98

**Comment by drewish** [comment]
I just noticed that there's a [cast](https://github.com/colebemis/feather/blob/master/icons/core/cast.svg) icon that's basically the RSS icon + a rectangle for a screen:

**Comment by mblode** [comment]
I made an RSS icon for a recent project. Does this suits feathericons?
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd" transform="translate(2 3)"><path stroke="currentColor" stroke-width="2" d="M1.095 7.958c5.01 1.022 8.925 4.937 9.947 9.947M1.095 0C10.515 1.048 17.952 8.484 19 17.905" stroke-linecap="round" stroke-linejoin="round" class="feather feather-rss"/><circle cx="2.211" cy="16.811" r="2.211" fill="currentColor"/></g></svg>
```

![rss](https://user-images.githubusercontent.com/7183998/31860270-919f6d44-b763-11e7-9e6e-0b736952993d.png)
