### ISSUE TITLE
Icon request: vk

### ISSUE THREAD

**Issue by alexantr** [feathericons/feather#14]
Icon name: vk
Logo of russian social network [VK](https://vk.com)
![vk com-96](https://cloud.githubusercontent.com/assets/4941848/26647359/ce9dcaca-4647-11e7-83b1-15b43d5622cc.png)
![vk com-100](https://cloud.githubusercontent.com/assets/4941848/26647361/d02cf7e4-4647-11e7-9524-304ae0c619e4.png)

**Comment by artemcodes** [comment]
This VK logo is no longer valid. You can get acquainted with the new design here https://github.com/feathericons/feather/issues/454

**Comment by locness3** [comment]
@artemcodes These are the same

**Comment by artemcodes** [comment]
@locness3 Can't you distinguish logos?

**Comment by alexantr** [comment]
VK Brandbook: https://vk.com/brand

**Comment by ahtohbi4** [comment]
What about this one?

<img width="454" alt="Снимок экрана 2019-08-19 в 14 00 28" src="https://user-images.githubusercontent.com/3686790/63260856-bf2a3300-c28a-11e9-8a13-f032de66f7a6.png">

<img width="490" alt="Снимок экрана 2019-08-19 в 14 03 12" src="https://user-images.githubusercontent.com/3686790/63260860-c2bdba00-c28a-11e9-9d69-3bcbb523a2cd.png">

**Comment by locness3** [comment]
Great!

**Comment by alexantr** [comment]
#763 I think I can close this issue due
