### ISSUE TITLE
Icon request: Medium logo

### ISSUE THREAD

**Issue by harryparkdotio** [feathericons/feather#154]
- [Medium](https://medium.com/)
- Example: a link on a portfolio website

![174858](https://user-images.githubusercontent.com/11331772/28355496-982cbace-6ca7-11e7-856d-2dc4e8b70782.png)
![medium_logo1600](https://user-images.githubusercontent.com/11331772/28355498-99b0640e-6ca7-11e7-8d1f-d4eda9978ad2.png)

**Comment by PaulCWoods** [comment]
http://www.underconsideration.com/brandnew/archives/new_logo_for_medium_done_in_house.php?utm_source=feedly&utm_medium=webfeeds They have a new logo. Before you do too much work ;)

**Comment by lndgalante** [comment]
Any news on this logo?

**Comment by elvismdev** [comment]
I'd like to use this logo. Any updates on this?

**Comment by mittalyashu** [comment]
@locness3 @ahtohbi4 @johnletey

Here are my weird suggestions

| Weird suggestion 1 | Weird suggestion 2 |
| --- | --- |
| ![Figma_lOg2gxWHAx](https://user-images.githubusercontent.com/29014463/61765573-4060e800-adfb-11e9-99a8-90044b6406bb.png) | ![Figma_gxU5UCtYJu](https://user-images.githubusercontent.com/29014463/61765578-43f46f00-adfb-11e9-8250-a06eb22a8d7d.png) |

**Comment by locness3** [comment]
I agree, they are weird lol.

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).

**Comment by krrohitch** [comment]
If anyone needs this, you can find it here - [Figma file](https://www.figma.com/file/igAYKQcZytsnVGbMV0Nm7D/Feather-Icons-krrohitch?node-id=0%3A1)

**Comment by PeterShaggyNoble** [comment]
Brand icons have been deprecated here; this one is [available from Simple Icons](https://simpleicons.org/?q=Medium).

[![Medium](https://user-images.githubusercontent.com/15157491/88823829-729ae780-d1bd-11ea-89a3-77453d99c19e.png)](https://simpleicons.org/?q=Medium)
