### ISSUE TITLE
Icon groups

### ISSUE THREAD

**Issue by piotrkulpinski** [feathericons/feather#163]
Hi @colebemis 

I'm sure I saw some kind of icon groups for Feather some time ago but they're gone for some reason.
Do you think it'd be possible to bring them back? 
I understand it may be easier to manage for you if they're all in the same directory but it's hard to find a particular icon on the site currently.

Maybe you could group them just on the site if that's easier?

Cheers, Piotrek

**Comment by colebemis** [comment]
We added icons [tags](https://github.com/feathericons/feather/blob/master/src/tags.json) that can be searched on feathericons.com. I'm going to close this issue because I think the new search feature addresses this issue.
