### ISSUE TITLE
Icon request: YouTube

### ISSUE THREAD

**Issue by thelaith** [feathericons/feather#169]
I wish to request a YouTube icon as there are other popular social media icons, but I was surprised to find out a YouTube Icon didn't exist. It would be used for social media linking and the likes.
There's social media icons on almost every popular website, so I definitely think it'd be useful.

https://i.imgur.com/6yOUlDF.png
https://i.imgur.com/G4xkSNj.png
https://i.imgur.com/im8pRWD.png

In their respective colors or in feather colours.

**Comment by alexdaniels11** [comment]
![youtube1600](https://user-images.githubusercontent.com/8548846/29327284-a45eca10-81bc-11e7-8b0d-286568873dfb.png)

**Comment by alexdaniels11** [comment]
![youtube-icon](https://user-images.githubusercontent.com/8548846/29327665-e39a25f2-81bd-11e7-977c-9aca93e119ea.png)

**Comment by thelaith** [comment]
I see you've moved it to done on Trello, but i can't find it in the feathericons overview @colebemis - Is it because it hasn't been uploaded yet? :)

**Comment by colebemis** [comment]
Yes, the Kanban board is for me to keep track of icons I've designed but not necessarily released yet. I have a few icons sitting on my machine that I'll release shortly 👍
