### ISSUE TITLE
icon request: Programming languages Logos

### ISSUE THREAD

**Issue by dags170291** [feathericons/feather#183]
Hi sorry to bother again but is it possible to get icons for various programming languages? such as HTML, CSS, JS, Node, Java, etc:
<img width="507" alt="screen shot 2017-09-10 at 1 35 07 pm copy" src="https://user-images.githubusercontent.com/6403926/30252861-3c9931f8-9626-11e7-88ca-43221c519118.png">

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
