### ISSUE TITLE
Copy SVG code to clipboard

### ISSUE THREAD

**Issue by colmtuite** [feathericons/feather#189]
I use inline SVGs almost exclusively for performance reasons. When I'm building out a UI and I need an icon, I want to be able to go somewhere, grab it, and paste it into my code.

So, it would be really useful if there was a button on the website to copy an icon to the clipboard.

**Comment by andrew-anguiano** [comment]
Is there a repo for the website that I could contribute to? I’d be happy to take a look at this.

**Comment by colebemis** [comment]
The code for the website is on the `site` branch: https://github.com/colebemis/feather/tree/site. You could open a pull request on that branch.

If you do decide to take this on, I'd appreciate if ran your design for this feature by me before you put too much effort in. Thanks!

**Comment by colebemis** [comment]
I'm going to move this issue to the [feathericons/feathericons.com](https://github.com/feathericons/feathericons.com) repo.
