### ISSUE TITLE
Icon request: Key

### ISSUE THREAD

**Issue by danbovey** [feathericons/feather#207]
> If you'd like to request an icon, please provide the following information:
> - icon name
> - at least one use case
> - screenshots of similar icons
>
> Please create one issue for each icon request.

Icon name: `key`
Use case: Icon to represent login/credentials
Examples:

![noun_1299202_cc](https://user-images.githubusercontent.com/1503076/31796729-d56dde2c-b522-11e7-856c-2749b29be030.png)![noun_894516_cc](https://user-images.githubusercontent.com/1503076/31796731-d88f47c6-b522-11e7-8c1e-8b2a79611d86.png)

**Comment by heyarne** [comment]
I would really like to have it as well. I would like to have it to represent PGP keys.

**Comment by colebemis** [comment]
@ashygee Nice! I'm liking `A` better for its simplicity. I feel like the key is looking smaller than the other icons (less _optical volume_). Have you tried rotating the key by 90° so it can take up a little more space? Example: 
![image](https://user-images.githubusercontent.com/4608155/51516802-6f0af100-1dcd-11e9-9ed2-a8838d40efb4.png)

**Comment by ashygee** [comment]
<img width="132" alt="screenshot 2019-01-23 22 42 12" src="https://user-images.githubusercontent.com/10384315/51659674-25064480-1f60-11e9-8b1c-db231e412e2b.png">

@colebemis rotated 45° and lengthened the stem of the key. Thoughts?

**Comment by colebemis** [comment]
@ashygee Can you share the Figma link for this with me? It's probably easier to make comments directly in the doc.

**Comment by colebemis** [comment]
Looking now 👍

**Comment by ashygee** [comment]
Close was a mistake. Hit the wrong button on mobile

**Comment by ashygee** [comment]
#520 will add this to the library. Closing this issue.
