### ISSUE TITLE
Icon request: Keybase

### ISSUE THREAD

**Issue by heyarne** [feathericons/feather#209]
To extend the set of available social icons, I'd like to request a [keybase icon](https://keybase.io).
Keybase is an app that's (amongst other things) joining multiple different online identities and enabling you to connect them with a key, making secure online communication less of a hassle.

The logo looks like this:
![screen shot 2017-10-22 at 23 12 54](https://user-images.githubusercontent.com/525780/31866335-92c4e65c-b77e-11e7-88d3-5026d4aaa1e5.png)

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
