### ISSUE TITLE
Icon Request: Camera Lens

### ISSUE THREAD

**Issue by rehatkathuria** [feathericons/feather#221]
If you'd like to request an icon, please provide the following information:
- Icon name: Camera Lens
- Use Case: I'm designing a section where there's EXIF information related to a photo including information about the lens and I think a camera lens icon would be lovely!
- Example Icon: https://thenounproject.com/search/?q=lens&i=1037121

**Comment by colebemis** [comment]
Would the `aperture` icon fit your needs?
 https://github.com/colebemis/feather/blob/master/icons/aperture.svg

**Comment by rehatkathuria** [comment]
I'm already using that to display the f stop for the exif data. Similarly, I'm using the camera icon itself to display information about the camera model.

**Comment by rehatkathuria** [comment]
😅

**Comment by MarcelloTheArcane** [comment]
Is this too simplistic?

![image](https://user-images.githubusercontent.com/21159570/61515503-abc14900-a9fa-11e9-838d-c3651fe67151.png)

**Comment by locness3** [comment]
Perfect! Could you give the Figma link and make sure to follow #171 ?

**Comment by MarcelloTheArcane** [comment]
I've cloned the existing repository, so it's on the bottom of [here](https://www.figma.com/file/kbBrVCZ84E8ZazGrBxzyTc/Feather-Component-Library-(Copy)?node-id=0%3A1).

Alternatively, the SVG:
```html
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" xmlns="http://www.w3.org/2000/svg">
  <circle cx="12" cy="12" r="10" stroke="inherit" stroke-width="inherit"/>
  <path d="M18 12C18 9 15.3137 6 12 6" stroke="inherit" stroke-width="inherit" stroke-linecap="round"/>
</svg>
```
