### ISSUE TITLE
Icon request: Hard drive / Device

### ISSUE THREAD

**Issue by danbovey** [feathericons/feather#223]
Icon name: `hdd`
Use case: Icon to represent a hard drive, external hard drive or similar usb device
Examples:

Modified the `inbox` icon by flattening the middle line and added circles from the `info` icon for consistency.
![image](https://user-images.githubusercontent.com/1503076/32894810-dcef86be-cad5-11e7-8172-4aac4a9bf70d.png)

SVG for above:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><polyline fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" points="22,13 22,13 22,13 2,13 2,13 2,13"/><path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="M5.47 5.19L2 13v5c0 1.104.896 2 2 2h16c1.104 0 2-.896 2-2v-5l-3.47-7.81C18.21 4.466 17.492 4 16.7 4H7.3c-.792 0-1.51.466-1.83 1.19z"/><line fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" x1="18.125" y1="16.5" x2="18.125" y2="16.5"/><line fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" x1="14.875" y1="16.5" x2="14.875" y2="16.5"/></svg>
```

**Comment by danbovey** [comment]
👍

**Comment by MarcelloTheArcane** [comment]
USB:
![image](https://user-images.githubusercontent.com/21159570/61532559-0de17480-aa22-11e9-9e04-b7af50dc0ed5.png)
![image](https://user-images.githubusercontent.com/21159570/61532574-1934a000-aa22-11e9-9f2d-b975715935c9.png)

**Comment by MarcelloTheArcane** [comment]
Also storage:
![image](https://user-images.githubusercontent.com/21159570/61533459-e0e29100-aa24-11e9-9639-876de5a0f881.png)
![image](https://user-images.githubusercontent.com/21159570/61533446-d627fc00-aa24-11e9-9508-a54a61cd5a7c.png)

**Comment by locness3** [comment]
I think the edges connecting the cover and front side of the storage look too sharp

**Comment by MarcelloTheArcane** [comment]
Less bad on the small icon which is what it is designed for. 

I'm not sure how to soften the corners using figma, which is the only thing...

**Comment by locness3** [comment]
Well, that's not bad, since the issue is closed, and the hard drive icon is already here. But you can create an new issue for `usb`
