### ISSUE TITLE
Solid (filled) icon family

### ISSUE THREAD

**Issue by sderakhshanjan** [feathericons/feather#233]
Do you think it is possible to create solid (filled) icon family?

**Comment by duhseekoh** [comment]
This would be nice. Trying to use this in React Native, which requires a conversion from svg -> font. When it's a font, can't define what the fill of the shape is going to be.

would be nice to have something like...
`heart` AND `heart-filled`

**Comment by colebemis** [comment]
Thanks for the suggestion! However, I'm going to close this for the reason explained in this issue https://github.com/colebemis/feather/issues/225#issuecomment-345473232

**Comment by reepush** [comment]
@colebemis Unfortunatly it's not a solution for React Native :(

**Comment by eonist** [comment]
I guess you could get the outlines from the feather.ttf and make svg outlines one by one. Cant seem to find anyone having done this yet. Ping me if someone does 🙏 currently using the font, but svgs are better IMO.

**Comment by waterplea** [comment]
@colebemis some icons that could in theory be filled by your suggestion are made with single path, rendering it impossible to fill only "fillable" part. See example below for `phone-call` icon:
![image](https://user-images.githubusercontent.com/11832552/216533259-758cf3a6-8ac9-4089-8ce6-384cbb525522.png)
It would be great if it could be broken into 2 paths with waves having explicit `fill="none"`, this way we could only fill the necessary part.
