### ISSUE TITLE
Icon request: code

### ISSUE THREAD

**Issue by alexantr** [feathericons/feather#24]
Icon name: code
Icon for source code.
Examples:
![ic_code_black_24dp](https://cloud.githubusercontent.com/assets/4941848/26653851/341b56e6-465d-11e7-8f97-85a1df81b92b.png)
![source code-104](https://cloud.githubusercontent.com/assets/4941848/26654034/de7c0bb2-465d-11e7-8110-62cb8f77b6fa.png)

**Comment by spaceywolfi** [comment]
:+1: yes please this icon would be great
