### ISSUE TITLE
Icon request: firefox

### ISSUE THREAD

**Issue by alexantr** [feathericons/feather#25]
Firefox icon to keep company with chrome icon.
Example:
![firefox-100](https://cloud.githubusercontent.com/assets/4941848/26654170/6d921198-465e-11e7-938b-bf92a9146703.png)

**Comment by colebemis** [comment]
I wish the Firefox icon was as simple as Chrome! 😄

**Comment by twtduck** [comment]
@colebemis Any update on when this might be added? I'm thinking about creating a solution of my own if it's still going to take several weeks.

Merry Christmas/Happy Holidays, friend!

**Comment by andyhqtran** [comment]
Wondering if there are still plans for this and Edge / IE 😄

**Comment by xypnox** [comment]
Firefox has simplified its icons, we can use the parent icon:

![image](https://user-images.githubusercontent.com/25076171/60160582-49b65f00-9813-11e9-9a67-ddf2d24e0a75.png)

which is much easier to design and also more legible for small sizes!

**Comment by locness3** [comment]
> Firefox has simplified its icons, we can use the parent icon:
> 
> ![image](https://user-images.githubusercontent.com/25076171/60160582-49b65f00-9813-11e9-9a67-ddf2d24e0a75.png)
> 
> which is much easier to design and also more legible for small sizes!

No, this icon is for the Firefox "ecosystem" (firefox send, firefox accounts, firefox monitor...). The browser still have its "traditional" icon. But that's a great idea, idk

**Comment by alexantr** [comment]
#763 I think I can close this issue due

**Comment by locness3** [comment]
@alexantr is simpleicons ok for yuou ?

**Comment by alexantr** [comment]
@locness3 Yes. Almost all simpleicons are ok for me.
