### ISSUE TITLE
Documentation for attributes

### ISSUE THREAD

**Issue by antigone2** [feathericons/feather#270]
I would just like to suggest some documentation for usage of attributes, like 'fill' accepts colors, etc.

**Comment by colebemis** [comment]
Any valid `<svg>` attribute can used in the `attrs` object. As it says in the README, key-value pairs in the `attrs` object will be directly mapped to attributes on the `<svg>` tag (e.g. { foo: 'bar' } maps to foo="bar"). Here are the docs for the valid `<svg>` attributes: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg#Attributes

Hope this helps. If you'd like, I encourage you to open a PR to clarify the parts of the docs that are confusing or unclear. Documentation contributions are super helpful 😄

**Comment by antigone2** [comment]
Sorry, I did not mean to suggest that there are any confusing or unclear parts of the docs. I just felt, that in the section [Usage](https://github.com/feathericons/feather#3-use-1), could be mentioned five basic attributes to work with icons: fill, stroke-line(bevel,round,mitter),stroke,stroke-width,width+height. On the other hand, it could make docs too large, ergo confusing, so ... just a suggestion. Anyway thank for your answer, icons and have a great day!

**Comment by colebemis** [comment]
Added some documentation about SVG attributes here: https://github.com/feathericons/feather/blob/master/README.md#feathericonsnametosvgattrs
