### ISSUE TITLE
Icon Request: Diaspora

### ISSUE THREAD

**Issue by tetris4** [feathericons/feather#272]
- Name: Diaspora
- Usage: Linking to personal profile
- Screenshots:![screenshot_20180113_200756](https://user-images.githubusercontent.com/1158465/34909235-7c3c8cfe-f89d-11e7-97be-41e89fc55af3.png)
- Project website: [joindiaspora.com](https://joindiaspora.com/)

Thank you for creating this great icon set and making it available under an open source license.

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
