### ISSUE TITLE
Icon Request: Mastodon

### ISSUE THREAD

**Issue by tetris4** [feathericons/feather#273]
- Name: Mastodon
- Use case: Linking to personal profile
- Screenshots:
![screenshot_20180113_210441](https://user-images.githubusercontent.com/1158465/34909655-65ea1ec8-f8a5-11e7-9b74-29faab13498b.png)

- Project website: https://joinmastodon.org/

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
