### ISSUE TITLE
Icon Request: JSFiddle

### ISSUE THREAD

**Issue by oskarkrawczyk** [feathericons/feather#284]
Name: JSFiddle
Usage: Linking to personal profile or action to the POST API (editing code from a POST request)
Screenshots: 

<img width="80" alt="screen shot 2018-01-18 at 15 25 39" src="https://user-images.githubusercontent.com/34213/35102674-de9e71a4-fc63-11e7-94e6-cb54f32f71a4.png">

Project website: jsfiddle.net

**Comment by johnletey** [comment]
@colebemis @locness3 @oskarkrawczyk Here's what I [have so far](https://www.figma.com/file/8lDNWxoeK8Ft0UFHtccKGC/jsfiddle) ... not quite sure if it follows #171 though

**Comment by locness3** [comment]
> @colebemis @locness3 @oskarkrawczyk Here's what I [have so far](https://www.figma.com/file/8lDNWxoeK8Ft0UFHtccKGC/jsfiddle) ... not quite sure if it follows #171 though

#171 is clear : "No fills"

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
