### ISSUE TITLE
Icon Request: Naver LINE

### ISSUE THREAD

**Issue by brianclemens** [feathericons/feather#297]
Icon name: LINE
Use case: Linking to LINE profile, indicating LINE username
Project website: [http://line.me/logo/guideline/en](http://line.me/logo/guideline/en)
Logo samples:
![LINE Logo](https://camo.githubusercontent.com/564036504b76c84af19353e39e7155a1e89f15f0/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f323634303031312f313739373137312f39643732373464632d366162332d313165332d383065622d3161383534333833373433312e6a7067)

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
