### ISSUE TITLE
Icon Request: Emoji/Emoticons Icon

### ISSUE THREAD

**Issue by kurisubrooks** [feathericons/feather#31]
Just a simple smiley face will do for this one. Useful for emoji pickers

Example:
![image](https://cloud.githubusercontent.com/assets/6291467/26705941/e1c9089a-477c-11e7-9080-0aec4d2fd91f.png)

**Comment by cassiewallace** [comment]
I second this one.

**Comment by thiagotomasi** [comment]
Hey @kurisubrooks and @cassiewallace here is my proposal to this one: ![emoji](https://user-images.githubusercontent.com/4387026/28340866-f1f4bcc0-6c19-11e7-9518-af105a521921.png)

And the file is here: [emoji.zip](https://github.com/colebemis/feather/files/1157346/emoji.zip)

**Comment by austenpayan** [comment]
+1

**Comment by Hongbo-Miao** [comment]
Another one
![image](https://user-images.githubusercontent.com/3375461/37324929-e644ded4-2648-11e8-935e-d0cda6bcadd8.png)

**Comment by apuntovanini** [comment]
Hi! Any news regarding this one?

**Comment by Kornflexx** [comment]
+1
