### ISSUE TITLE
Localization/Filipino Translation

### ISSUE THREAD

**Issue by jcpuzs1** [feathericons/feather#315]
I want to contribute by means of localizing some of your file to Filipino Language.

**Comment by colebemis** [comment]
Awesome! Which document would you like to translate? README.md?

**Comment by jcpuzs1** [comment]
as long as I can have 1000 words or more.  I mean minimum of 1000 words 👍

**Comment by colebemis** [comment]
Cool, what's special about 1000 words?

**Comment by jcpuzs1** [comment]
Good morning Sir, I need it to present in utopian 😀😀. Their minimum number of words is 1000. So which is it sir?

**Comment by colebemis** [comment]
I don't think Feather is really in need of any translation at this point. You're efforts would probably be more impactful on a bigger project like [glamorous](https://github.com/paypal/glamorous) or [styled-components](https://github.com/styled-components/styled-components).

**Comment by jcpuzs1** [comment]
okay sir thank you for ur time
