### ISSUE TITLE
Icon request: Archive

### ISSUE THREAD

**Issue by Hongbo-Miao** [feathericons/feather#320]
Archive icon is very useful for mail client.
Something like below:

![image](https://user-images.githubusercontent.com/3375461/36395788-c8f5620c-156f-11e8-8836-53bec9794ed1.png)

Right now it is only one icon missing for my app to switch to feather icon.
Thanks

**Comment by humphreybc** [comment]
Have you tried either the ‘box’ or ‘folder’ icons instead?

**Comment by Hongbo-Miao** [comment]
Hi @humphreybc I did a quick survey, people cannot recognize the function of it when use ‘box’ or ‘folder’ icons.
