### ISSUE TITLE
How to use chevron-up/chevron-down

### ISSUE THREAD

**Issue by mpadovan** [feathericons/feather#331]
I can't use the `feather.icons.chevronUp.toSvg();` function but with `feather.icons.activity.toSvg();`  works fine. How to display chevrons then?

**Comment by colebemis** [comment]
Looks like you're using camel case instead of kebab case. Try this instead:

```diff
- feather.icons.chevronUp.toSvg()
+ feather.icons['chevron-up'].toSvg()
```

Hope that helps 👍

**Comment by mpadovan** [comment]
Thanks it works! But maybe you should write the usage inside the docs
