### ISSUE TITLE
Icon request: Corporate / Customer / Building

### ISSUE THREAD

**Issue by mhosman** [feathericons/feather#352]
- Corporate / Customer / Building
- An icon to represent a customer or corporation
- Screenshots of similar icons:

![65999-200](https://user-images.githubusercontent.com/5334175/37168591-1c2b2764-22e4-11e8-92db-b3af06c7a7a7.png)
![office_building-512](https://user-images.githubusercontent.com/5334175/37168592-1e4c9230-22e4-11e8-8a84-8b51101eb6db.png)

**Comment by mhosman** [comment]
Sorry, duplicated with #55

**Comment by colebemis** [comment]
@mhosman good catch! I'm going to go ahead and close this one as a duplicate.
