### ISSUE TITLE
Icon Request: Node.js

### ISSUE THREAD

**Issue by brandonweiss** [feathericons/feather#372]
Name: JavaScript
Use case: Indicating something is a Node.js library or written in Node.js
Screenshot:

![nodejs-logo-fbe122e377-seeklogo com](https://user-images.githubusercontent.com/4727/38117885-69734bbc-336c-11e8-8653-86b0fa071896.png)

![nodejs-new-pantone-black](https://user-images.githubusercontent.com/4727/38117898-75c704e4-336c-11e8-82bb-dffd73f55e94.png)

**Comment by colebemis** [comment]
Do you think a simple hexagon could work? Something like this:

![image](https://user-images.githubusercontent.com/4608155/38125110-013909e4-339c-11e8-8ad7-46a8663fce99.png)
https://thenounproject.com/search/?q=hexagon&i=1158005

**Comment by brandonweiss** [comment]
Hrm. I would say out-of-context it's definitely not clear. In-context, maybe?

It's unfortunate that most languages don't have a recognizable mark, and it gets even harder if you're trying to represent it in a minimalist, less-detailed style. A language like Ruby is highly-recognizable—a Ruby as a mark could be detailed or simple and people will still know it's a Ruby. Even non-Rubyists will know it. But with Node.js, I don't think even some Nodists (?) would recognize the green octagon “o”. I use Node pretty regularly and I didn't know that was one of the marks.

Another alternative might be nested octagons? It might look more like an “o” that way, or perhaps call to mind the “e”? AWS uses a similar shape to represent their SDKs in different languages.

<img width="1081" alt="screen shot 2018-03-29 at 10 12 42 pm" src="https://user-images.githubusercontent.com/4727/38125446-5dc86df6-339e-11e8-945f-19c824c45c21.png">

Rather than try to make a mark for each one they use color to differentiate the different languages, but that wouldn't work here.

**Comment by colebemis** [comment]
I feel like a green hexagon in context could work. It looks like node.js uses hexagon as their simplified logo:

![image](https://user-images.githubusercontent.com/4608155/38125610-96df26c4-339f-11e8-8ead-aa40e77132b0.png)

**Comment by brandonweiss** [comment]
@colebemis 👍

**Comment by brandonweiss** [comment]
How are you imagining using green? Would this be the first icon that has color? Or are you imagining it in black and users could style it with the color if they wanted?

**Comment by colebemis** [comment]
I'm just planning to make a black `hexagon` icon that people could style to work as a `node.js` icon.

**Comment by brandonweiss** [comment]
That sounds great! 💪
