### ISSUE TITLE
.gitattributes

### ISSUE THREAD

**Issue by alexantr** [feathericons/feather#40]
I'm not sure if `npm` considers `.gitattributes` but this file will be usefull to ignore some files and folders unnecessary in npm package.

For example:
```
/.gitattributes       export-ignore
/.gitignore           export-ignore
/.npmignore           export-ignore
/_includes            export-ignore
/assets               export-ignore
/bin                  export-ignore
/_config.yml          export-ignore
/Gemfile              export-ignore
/Gemfile.lock         export-ignore
/index.html           export-ignore
/ISSUE_TEMPLATE.md    export-ignore
/style.css            export-ignore
/svgo-config.yml      export-ignore
```

**Comment by alexantr** [comment]
Another good reason to use `.gitattributes`: `build-zip.sh` not needed anymore, bcs github will create archives for release only with files not ignored in `.gitattributes`.

**Comment by colebemis** [comment]
Thanks! Didn't know about `.gitattributes`. I'll look into this.
