### ISSUE TITLE
The dot does not show up for Instagram icon in Sketch.app

### ISSUE THREAD

**Issue by larrychen** [feathericons/feather#425]
<img width="652" alt="screen shot 2018-05-15 at 1 42 52 pm" src="https://user-images.githubusercontent.com/910859/40082473-f3633adc-5845-11e8-85b3-ead23fb658e2.png">

Any way to fix this without drawing a shape with fill?

**Comment by colebemis** [comment]
Have you tried [sketch-feather](https://github.com/feathericons/sketch-feather)?

**Comment by larrychen** [comment]
Oh great! thanks!
