### ISSUE TITLE
Feature Request: Search and Icon Tagging System

### ISSUE THREAD

**Issue by kurisubrooks** [feathericons/feather#44]
For example, "square" can be re-used as a "stop" symbol for media-controls, referencing #42

**Comment by kurisubrooks** [comment]
Perhaps a build system that reasons from a JSON file that duplicates icons for the Netlify instance only

**Comment by colebemis** [comment]
See conversation on #45

**Comment by alexantr** [comment]
If tagging system will be integrated you can move all icons to one directory. Because some icons can belong different categories.
And this will be better for automated tools which inluding icons on page only by icon name - no need to search them in subfolders.

**Comment by colebemis** [comment]
I've thought about that too. Are you suggesting removing the concept of categories and displaying all icons as a single group on the website? Would categories then become general tags? For example, the `cloud` and `sun` icons might both have a `weather` tag?

**Comment by alexantr** [comment]
By default you can show all icons in alphabet and show list of all tags in switcher.

**Comment by alexantr** [comment]
And search field too of course.

**Comment by colebemis** [comment]
What do you mean by "show list of all tags in a switcher"? Do you have examples of other websites that do something similar?

**Comment by alexantr** [comment]
Like on http://www.iconarchive.com/alphabet-list.html
Alphabet, newest, popular, random, by category (meaning icon can have some of categories)

**Comment by alexantr** [comment]
Another variant of catalog: https://www.iconfinder.com/search/?q=
Filtering by switcher: https://isotope.metafizzy.co/filtering.html

**Comment by alexantr** [comment]
See example: https://yashkin.by/feathericons/
For example added `square` icon to category "media and controls".

**Comment by wappsdotgr** [comment]
If you end up using the listjs lib (it rox btw), see #45, and you want to avoid a json file, a quick (dirty) solution would be a txt file and some javascript as shown here: https://jsfiddle.net/jampascript/cn71shgL/

**Comment by Swizz** [comment]
And what about symlink ? Creating an alias will be as simple as creating a symlink to the svg file, to keep module as directory convention.

And, when we will work on the bundler, alias/symlink will be compiled as a "refer to" or something like.

**Comment by acicali** [comment]
@alexantr this is very nice: https://yashkin.by/feathericons/

**Comment by YurySolovyov** [comment]
How about just plain search field that filters icons by label?

**Comment by colebemis** [comment]
You can now search for icons on https://feathericons.com 🎉 . The search uses both the icon name and its tags. Tags are managed by `src/tags.json` (https://github.com/feathericons/feather/blob/master/src/tags.json). Feel free to contribute more tags!
