### ISSUE TITLE
Icon request: ORCID

### ISSUE THREAD

**Issue by Guillawme** [feathericons/feather#440]
- icon name: ORCID
- at least one use case: can be used as a "social icon" in website themes using the feather icons, like [Minimo](http://minimo.netlify.com/)
- screenshots of similar icons: see https://orcid.org/favicon.ico or screenshot below
![screenshot-2018-5-24 cran - package knitr](https://user-images.githubusercontent.com/9656546/40510389-cea32ce6-5f59-11e8-8ada-09e8c944536a.png)

**Comment by raheems** [comment]
I need that, too!

**Comment by MarcelloTheArcane** [comment]
See #763

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
