### ISSUE TITLE
Cannot read property toSvg

### ISSUE THREAD

**Issue by kodeine** [feathericons/feather#443]
Getting the following error, any idea's?

![image](https://user-images.githubusercontent.com/8620059/40758609-d11c7a8c-6453-11e8-8a55-eee0e0704d65.png)

**Comment by colebemis** [comment]
Could you make a [CodePen](https://codepen.io/) to reproduce this error? Here's a Feather CodePen template to get you started: https://codepen.io/pen?template=WOJZdM

**Comment by christophlieck** [comment]
I've had the same trouble when I tried to set the data-feather attribute dynamically in a php template:

`<i data-feather="{icon}"></i>`

Weird enough the dynamic replacement worked but all subsequent icons didn't render and throw this error.

**Comment by abner-carvalho** [comment]
I have the same error here, but in my case i'm using Wordpress.

When i put a feather icon in the_content() section i'm getting this error.

**Comment by wdebusschere** [comment]
This happens when the attribute data-feather is empty..
`data-feather=""`

**Comment by emilas44** [comment]
we just need an if statement before rendering? To check if there is that icon?

**Comment by gamefanpage** [comment]
I have the same issue it's appear if you are not auth on your website and browse as guest
but if you are auth as admin or members no more errors

Uncaught TypeError: Cannot read property 'toSvg' of undefined
    at feather.min.js:12
    at feather.min.js:12
    at Array.forEach (<anonymous>)
    at Object.n.default [as replace] (feather.min.js:12)
    at terms:368

**Comment by locness3** [comment]
>I have the same issue it's appear if you are not auth on your website and browse as guest ...

@gamefanpage Does it appear with empty icon names or always ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kedomingo** [comment]
Hi, I encountered the same issue. What happened in my case was I mistyped one icon name (`slider` instead of `sliders`) but all the icons did not load. I must say it was kinda hard to debug

**Comment by adigunsherif** [comment]
This happens when you put in a non-existing icon name or you misspelt an icon name.

**Comment by parthdevloper** [comment]
**If fixed this issue in ANGULAR 10**

Here is my code : 

```
<div class="card icon-card cursor-pointer text-center mb-2 mx-50" *ngFor="let dat of data | keyvalue">
     <div class="card-body">
         <div class="icon-wrapper">
              <i [data-feather]="dat.key"></i>
         </div>
       <p class="icon-name text-truncate mb-0 mt-1">{{ dat.key }}</p>
     </div>
</div>
```

component.ts


```
public  json = require('feather-icons/dist/icons.json');
public data;

ngOnInit() {
  this.data = this.json;
}
```

Here key element is `square brackets` I mean `[data-feather]`.

**Comment by ProteanCode** [comment]
> This happens when the attribute data-feather is empty or when the icon doesn't exist..
> `data-feather=""`
> 
> This should be fixed, because an empty or invalid icon name causes all icons to be NOT displayed

This was the problem in my case.

**Comment by kenanhodzic** [comment]
In my case it was icon name typo. Check if icon name exists.

**Comment by subdesign** [comment]
My problem was I fired a multi-rename in my IDE, and I accidentally updated an icon's name to a non existing one.
I figured it out when I added some console debugging to feather.js.

Add these lines to `node_modules/feather-icons/dist/feather.js` in the `replaceElement()` function, before the `.toSvg()` call:
```js
console.log(_icons2.default[name]);
console.log(name);
console.log('-----');
```
of course delete them after you end debugging.

**Comment by alexseif** [comment]
The issue here is that's it's very hard to debug, if you have a lot of icons in your page. So far I use this code every time this issue appears, and then manually check against the website to see which icon is misspelled. Can we have a more graceful fallback that doesn't just ruin all the other icons.

`$('[data-feather]').each(function (){console.log($(this).attr('data-feather'));});`
