### ISSUE TITLE
Dynamic change one icon to another

### ISSUE THREAD

**Issue by vip9** [feathericons/feather#447]
How to programatically (dynamically) change icon to another?
E.g. <i id="foo" data-feather="clock"> to "watch"?

**Comment by colebemis** [comment]
I'm not sure I know what you mean. Could you find an example of doing this with another icon set?

**Comment by vip9** [comment]
e.g. https://fontawesome.com/how-to-use/svg-with-js
 search for "Changing icons by changing class"

```
<button>Open up <i class="fa fa-angle-right"></i></button>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    $('button').on('click', function () {
      $(this)
        .find('[data-fa-i2svg]')
        .toggleClass('fa-angle-down')
        .toggleClass('fa-angle-right');
    });
  });
</script>

```

clicking a icon button changes that icon to another (here, an arrow)

**Comment by craigrodway** [comment]
If you have jQuery, this seems to work:

`$(".parent svg.feather.feather-circle").replaceWith(feather.icons.square.toSvg());`

Essentially - find the existing Feather-generated SVG element and replace it with a new one using the Feather JS function.

**Comment by colebemis** [comment]
@craigrodway's solution should work. If it works for you, feel free to close this issue.

**Comment by MarcelloTheArcane** [comment]
@craigrodway Or without jQuery:

```js
document.querySelector('.parent svg.feather.fether-circle').replaceWith(feather.icons.square.toSvg())
```

**Comment by fahadashiq12** [comment]
The answer to this question is quite elaborative to explain.

**Comment by tcs-ulli** [comment]
when i try this with: 
step.children[0].replaceWith(feather.icons["check"].toSvg({"stroke": "green"}));

the svg code shows in the rendered view, iam unsure what iam doing wrong

**Comment by rvalms** [comment]
mine quite worked, but the tag became string (like this "<svg>", not <svg>)
