### ISSUE TITLE
🐛 Import svgs to design tools fails on icons with "dots"

### ISSUE THREAD

**Issue by renatodeleao** [feathericons/feather#451]
*[AWESOME SET, THANK YOU! 💪]*
####  Description:
I've been running through an issue while import the svgs from the source folder into several design tools. Every icon that has a small dot (smartphoone, tablet, alert-triangle, alert-octagon, to name a few) does not import correctly.

![demo](https://dzwonsemrish7.cloudfront.net/items/2G3v033Z242R2g0d053e/Screen%20Recording%202018-06-22%20at%2009.47%20AM.gif?v=85899811)

Has anyone else experienced this?

#### possible causes & possible solution:
Icons are exported with strokes and probably most design tool run some kind of svg optimizer for paths (like [SVGO](https://github.com/svg/svgo/) ). Actually you can see this glitches happening in [SVGO online tool](https://jakearchibald.github.io/svgomg/) by tweaking some parameters ( Round average curves )

#### Possible Solutions
Have a source folder with stroke versions (not sure which design tool have you used to begin with), and have a `dist` folder, where strokes are expanded to outlines (shapes)

#### System:
macOS High Sierra 10.13.4

####  Tested Tools:
Affinity Designer 1.6.1
Sketch 50.2
Figma 3.0 (Both desktop wrapper 3.6.15 and web version)

**Comment by SirPole** [comment]
you can disable `convertShapeToPath` in svgo to stop this from happening.

**Comment by awrye** [comment]
Hello, I've run into this issue as well. I've created outlines and lined folders just as you had mentioned. I wanted to place them here for others to use as well.

[Feather.zip](https://github.com/feathericons/feather/files/2177276/Feather.zip)
