### ISSUE TITLE
Icon Request: vk

### ISSUE THREAD

**Issue by kristall000** [feathericons/feather#454]
Icon name: vk
Use case: Link/Button
Example: [fontawesome.com](https://fontawesome.com/icons/vk?style=brands) or [PSD](https://vk.com/doc75344642_449888252) & [EPS](https://vk.com/doc75344642_449888239)
![vk_logo](https://user-images.githubusercontent.com/13225484/42413527-1b4d52d0-822b-11e8-8e1c-b0f335bf1bb0.png)

**Comment by ahtohbi4** [comment]
Duplicate of #14

**Comment by colebemis** [comment]
Closing this because it's a duplicate of #14

**Comment by warshell** [comment]
any news on this icon request? thanks

**Comment by locness3** [comment]
#763 : brand icons are deprecated
