### ISSUE TITLE
Icon Request: Codesandbox

### ISSUE THREAD

**Issue by chetanraj** [feathericons/feather#480]
## Icon Request

* Icon name: Codesandbox
* Use case:
* Screenshots of similar icons: 
![codesandbox](http://cdn.embed.ly/providers/logos/codesandbox.png)

**Comment by colebemis** [comment]
Could `box` used as a simplified version of the codesandbox logo? https://github.com/feathericons/feather/blob/master/icons/box.svg

**Comment by csandman** [comment]
Gave it a shot

<img width="329" alt="code-sandbox" src="https://user-images.githubusercontent.com/9214195/55269840-27da2a00-526e-11e9-8944-6f2d7f8401b4.png">

SVG and Figma file
[code-sandbox.zip](https://github.com/feathericons/feather/files/3025021/code-sandbox.zip)

**Comment by locness3** [comment]
@csandman Great! View the guidelines at #171

**Comment by colebemis** [comment]
@csandman I updated all the hexagon-based icons in #567 so I went ahead and added a `codesandbox` icon. Thanks for the help!
