### ISSUE TITLE
elm-feather

### ISSUE THREAD

**Issue by 1602** [feathericons/feather#481]
This package is currently published under 1602 username, which causes an issue due to elm compiler bug (it generates javascript variable starting with digit). Fix might not be released any time soon which makes quite a bit of people unable to use this library.

So I'm looking for a new home for this library and wonder if [feathericons](https://github.com/feathericons) organisation would be a suitable place.

Let me know if you're okay with that and I will transfer ownership. If this is not okay I will pick some other org to move package. Thank you!

**Comment by colebemis** [comment]
Yeah, the `feathericons` org would be a great place for `elm-feather` feel free to transfer ownership and I'll add you as a member of the org :)

**Comment by 1602** [comment]
Github says "You don’t have the permission to create repositories on feathericons", so I guess I need this permission temporarily in order to transfer repo.

**Comment by colebemis** [comment]
Okay, I just invited you to be a member of the organization ✅

**Comment by 1602** [comment]
Thank you! I transferred ownership and published elm-feather under a new org name to elm registry. It appears that I still have rights to commit to elm-feather repository.
