### ISSUE TITLE
PHP Feather library

### ISSUE THREAD

**Issue by Pixelrobin** [feathericons/feather#494]
I made a PHP library for Feather.

https://github.com/Pixelrobin/php-feather

I'm still somewhat of a newbie, so I would love some guidance on it. It's not in a stable state at the moment, but I'm hoping to release it asap. Perhaps someday it will be worthy enough to be put in the README?

**Comment by colebemis** [comment]
Awesome! I don't know too much about PHP so I can't give you really give you guidance. Sorry about that.

When you feel like it's in a stable state, feel free to open a pull request adding it to the README 👍

**Comment by Pixelrobin** [comment]
https://github.com/feathericons/feather/pull/495
