### ISSUE TITLE
Icon Request: Contrast

### ISSUE THREAD

**Issue by schmidt-oliver** [feathericons/feather#496]
**Icon name**
contrast

**Use case**
For example on a webpage to change the color view for more accessibility.

**Screenshots of similar icons** 

![contrast-icon](https://user-images.githubusercontent.com/33413922/48255748-da1f6b00-e40d-11e8-87a3-5101ea6da370.png)

**Comment by csandman** [comment]
My friend gave it a shot:

![contrast-example](https://user-images.githubusercontent.com/9214195/55259935-6b687000-523d-11e9-9222-00d97f9e62ba.PNG)

[contrast-feather.zip](https://github.com/feathericons/feather/files/3024336/contrast-feather.zip)

**Comment by csandman** [comment]
This was made by @jonahallibone 

And here is a figma file for it:

[Contrast.fig.zip](https://github.com/feathericons/feather/files/3024668/Contrast.fig.zip)
