### ISSUE TITLE
Icon Request: AngelList

### ISSUE THREAD

**Issue by ronnyhaase** [feathericons/feather#501]
## Icon Request

* Icon name: AngelList
* Use case: Link / connect / follow on AngelList
* Screenshots of similar icons:
![angellist_logo](https://user-images.githubusercontent.com/714368/48545974-0845f480-e8bf-11e8-8d2b-f9099a181ca7.png)

**Comment by johnletey** [comment]
@colebemis @locness3 @ronnyhaase How does [this](https://www.figma.com/file/rvar0EQIIYbYlUMrJxwbIS/angellist) look?

**Comment by locness3** [comment]
> @colebemis @locness3 @ronnyhaase How does [this](https://www.figma.com/file/rvar0EQIIYbYlUMrJxwbIS/angellist) look?

Like I said, you shouldn't outline your icons.
BTW, did you really made it yourself or you just imported it from their brand kit ?

**Comment by johnletey** [comment]
> Like I said, you shouldn't outline your icons.

@locness3 What does that mean?

> BTW, did you really made it yourself or you just imported it from their brand kit ?

No ... just imported it as I thought it looks like a feather icon ... sorry, my bad ... I can make my one if you want!

**Comment by locness3** [comment]
> > Like I said, you shouldn't outline your icons.
> 
> @locness3 What does that mean?
> 
> > BTW, did you really made it yourself or you just imported it from their brand kit ?
> 
> No ... just imported it as I thought it looks like a feather icon ... sorry, my bad ... I can make my one if you want!

Outlining means that you will draw the contour, the outline. Feather Icons are not made like that.

**Comment by locness3** [comment]
> No ... just imported it as I thought it looks like a feather icon ...
That's truly bad.

**Comment by johnletey** [comment]
@locness3 I understand now ... it really is bad! I am extremely sorry and I will devote more time to actually designing this icon! Again, extremely sorry!

**Comment by locness3** [comment]
That's ok @johnletey .

**Comment by MarcelloTheArcane** [comment]
See #763
