### ISSUE TITLE
Icon Request: Rust

### ISSUE THREAD

**Issue by JoelEllis** [feathericons/feather#512]
## Icon Request

* Icon name: Rust Logo
* Use case: Representing the rust langage. 
* Screenshots of similar icons: ![rust](https://www.rust-lang.org/static/images/rust-logo-blk.svg)

**Comment by MarcelloTheArcane** [comment]
See #763

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
