### ISSUE TITLE
New Designer

### ISSUE THREAD

**Issue by JadedBlueEyes** [feathericons/feather#513]
One of my friends is willing to contribute some icons. He's a graphic designer. @colebemis is this OK? should I give him the go-ahead?
I'll manualy edit the code of each icon to be consistent with the others.

**Comment by colebemis** [comment]
@derpmarine168 He's welcome to give it a go :) I make no promises about merging in new icons though. I'll add them if I think they'd be a good fit. Currently, the design guidelines only exist in my head. I need to take the time to write them down 😅
