### ISSUE TITLE
Icon name not match with icon which showed

### ISSUE THREAD

**Issue by consciousnessdev** [feathericons/feather#543]
I use "react-native-vector-icons": "^6.2.0"

when i call component
`const down = ({ tintColor }) => (<Icon name="bluetooth" size={25} color={tintColor} />);`

it showing briefcase icon :
blob:https://feathericons.com/6f2f0f99-6adb-4877-b7d6-4384862ce0f6

Update :
i'd done updated to 6.3.0, but still facing same problem

home  [showing] map
cpu [showing] clouddownloado
info [showing] arrowsalt

**Comment by colebemis** [comment]
This seems like an problem with `react-native-vector-icons`. Can you move this issue to https://github.com/oblador/react-native-vector-icons?

**Comment by consciousnessdev** [comment]
> This seems like an problem with `react-native-vector-icons`. Can you move this issue to https://github.com/oblador/react-native-vector-icons?

ok, but those link when apps is released mode, but my problem when development mode

**Comment by consciousnessdev** [comment]
> > This seems like an problem with `react-native-vector-icons`. Can you move this issue to https://github.com/oblador/react-native-vector-icons?
> 
> ok, but those link when apps is released mode, my problem when development mode

Solved With
`react-native unlink react-native-vector-icons`
then
`react-native link react-native-vector-icons`
