### ISSUE TITLE
Icon Request: Utensils Icon

### ISSUE THREAD

**Issue by lukashambsch** [feathericons/feather#552]
## Icon Request

(May be related to https://github.com/feathericons/feather/issues/32, but is requesting a different icon)

* Icon name: utensils
* Use case: There are many food / fitness related apps that could use an icon to signify something related to food.
* Screenshots of similar icons:
Feather version of this font-awesome icon (https://fontawesome.com/icons/utensils?style=solid)
![screen shot 2019-03-02 at 8 04 42 pm](https://user-images.githubusercontent.com/7560008/53690808-89b67b00-3d26-11e9-8258-84d2ec0f708e.png)

**Comment by ashygee** [comment]
Icon:
<img width="30" alt="screenshot 2019-03-02 20 29 30" src="https://user-images.githubusercontent.com/10384315/53690985-e6676500-3d29-11e9-907b-9dee9e1ca65e.png">

Side-by-side example:
<img width="95" alt="screenshot 2019-03-02 20 29 25" src="https://user-images.githubusercontent.com/10384315/53690984-e6676500-3d29-11e9-960c-02aa6cf5a7e0.png">

@colebemis Here's an idea for this one. What do you think?

**Comment by colebemis** [comment]
Nice! Just curious, can we try a version with single-line handles? Maybe something similar to Nucleo's: 
![image](https://user-images.githubusercontent.com/4608155/53705016-487da400-3dd6-11e9-9802-4227fb7875f6.png)

**Comment by ashygee** [comment]
@colebemis yeah of course. I tried the single line for the fork and it just looked a lot like a trident to me. LOL! Happy to do something similar.

**Comment by lukashambsch** [comment]
Hey, any update on this?

I'm not a designer. But if it's okay with you, I'd be happy to hire someone to work on this.

**Comment by locness3** [comment]
@ashygee #171

**Comment by lukashambsch** [comment]
@ashygee @colebemis What do you guys think of these ones?

![Artboard_70px](https://user-images.githubusercontent.com/7560008/60018338-576bb900-9648-11e9-9031-98e884045d7e.png)
![Artboard_24px](https://user-images.githubusercontent.com/7560008/60018351-5e92c700-9648-11e9-98e7-fb35a6e2e7d6.png)

**Comment by locness3** [comment]
@lukashambsch Hmm... Please submit the svg to a pull so I can look more precisely. An image is not enough.

**Comment by lukashambsch** [comment]
@locness3 I created the pull request here: https://github.com/feathericons/feather/pull/629. Please let me know any changes that should be made.

**Comment by e1016** [comment]
I'm in a project looking for food icons too, I made this...

![food-icons](https://i.imgur.com/CPbrn6U.png)

[--> Drive link <--](https://drive.google.com/open?id=1ELlT_S1lNV4VN4Yg8v2ky-QtQS5Zhx37)

**Comment by locness3** [comment]
@e1016 You should post that both here and in #32 . If you want to submit, follow #171 .

**Comment by e1016** [comment]
Ok, thanks, I will check #171 but are you accepting [pull requests?](https://github.com/feathericons/feather/blob/master/CONTRIBUTING.md)

**Comment by johnletey** [comment]
@e1016 Kind of ... you can open pull requests ... but they are currently not being merged as the project owner, @colebemis, is currently really busy
