### ISSUE TITLE
Icon Request: Column

### ISSUE THREAD

**Issue by csandman** [feathericons/feather#565]
## Icon Request: column

* Icon name: column/columns
* Use case: to represent a split screen option.  an example would be in visual studio code, on the terminal and it is used to split the terminal into two columns
* Screenshots of similar icons:
Here is a sample I made by slightly modifying your layout icon, it should be very easy to replicate.  I simply moved the top bar up and centered the vertical line.
<img width="133" alt="feather-columns-filled" src="https://user-images.githubusercontent.com/9214195/55201192-4241d400-5198-11e9-9c5e-50266b010683.png">

Here is the version from font-awesome:
https://fontawesome.com/icons/columns?style=solid

If you can find the time, please add this one!  It should take long to make and it would be what pushes me over the edge to using this icon pack!

**Comment by mhosman** [comment]
This is already done!! Use the "layout" icon!

**Comment by csandman** [comment]
@mhosman as I said, I made this icon mockup from the layout icon.  I'm interested in an icon with 2 equal columns to represent a split screen, not one that appears as a sidebar and a header of a page like the layout icon does.

<img width="155" alt="Screenshot 2019-03-28 20 14 17" src="https://user-images.githubusercontent.com/9214195/55209965-809cba80-51bb-11e9-8ee7-58dda8c1420f.png">
 (original)

versus

<img width="133" alt="feather-columns-filled" src="https://user-images.githubusercontent.com/9214195/55209885-26035e80-51bb-11e9-8dba-28ef600010e8.png">
(the new requested version)

**Comment by locness3** [comment]
#171

**Comment by csandman** [comment]
I figured out how to use Figma and used the styleguides listed in #171 to make it on my own.  Here is a screenshot of the pixel layout:

![columns-image](https://user-images.githubusercontent.com/9214195/55258171-753ba480-5238-11e9-8b9d-44850ef73eca.PNG)

And here is the exported SVG:

[columns-feather.zip](https://github.com/feathericons/feather/files/3024180/columns-feather.zip)

Hope I went through the right process to get this added!

**Comment by colebemis** [comment]
@csandman Do you think the "header" is necessary for a `column` icon? What about something like this? 
![image](https://user-images.githubusercontent.com/4608155/55262480-1b80ad80-522b-11e9-930b-16472d9c89ae.png)

**Comment by csandman** [comment]
@colebemis I think the header helps to show that its a type of layout but if you'd rather the more minimalist look, that would work too.  By the way, in the future would it be helpful to include a .fig file with the svg to make it easier to modify?

**Comment by colebemis** [comment]
@csandman Yeah, I think I prefer the minimal version (without the header). Do you wanna try opening a PR? There are instructions on how to do that at the bottom of this comment: https://github.com/feathericons/feather/issues/171#issuecomment-455356985

I can walk you through it in more detail if those instructions are a little confusing.

Also, in the future, a figma link or `.fig` file would be super helpful, thanks!

**Comment by csandman** [comment]
@colebemis I would love to submit a pull request! It will be my first one on an open source project.  Would you prefer I name it column or columns?

Also, in order to do so I should for the repo, push to that, and then submit the pull request, correct?

**Comment by colebemis** [comment]
@csandman I left some comments on the PR 👍
