### ISSUE TITLE
Icon Request: Twitch icon

### ISSUE THREAD

**Issue by hammackj** [feathericons/feather#584]
## Icon Request

* Icon name: Twitch.tv Icon
* Use case: Twitch.tv social Icon
* Screenshots of similar icons:
Examples and brand info can be found here: https://www.twitch.tv/p/brand/

**Comment by johnletey** [comment]
@colebemis @locness3 @hammackj How does [this](https://www.figma.com/file/NGP8BVnpWJLPDE5ypIUR5fx7/twitch) look?

I was having a hard time following #171 ... would love a little feedback/guidance if possible!

**Comment by locness3** [comment]
> I was having a hard time following #171 ... would love a little feedback/guidance if possible!

What made you have a hard time exactly ?

**Comment by johnletey** [comment]
> What made you have a hard time exactly ?

@locness3 Well ... did I follow the guidelines correctly? I just found the guidelines a bit confusing as this is a logo and not a circle/square as described in the guidelines.

**Comment by locness3** [comment]
> > What made you have a hard time exactly ?
> 
> @locness3 Well ... did I follow the guidelines correctly? I just found the guidelines a bit confusing as this is a logo and not a circle/square as described in the guidelines.

You could try making a simplified rounded version of the logo, just look a other logos to see what I mean

**Comment by johnletey** [comment]
@locness3 I have updated the icon ... now it looks more like a feather icon! I have two updated icons -- one with the "eyes" in the "center" and the other with the "eyes" in the "upper-right"

**Comment by locness3** [comment]
> @locness3 I have updated the icon ... now it looks more like a feather icon! I have two updated icons -- one with the "eyes" in the "center" and the other with the "eyes" in the "upper-right"

That looks great! But please don't make outlines. Use a simpler path with a centered border. You can look at other icons to see what I mean.

**Comment by johnletey** [comment]
@locness3 Have updated the logo (P.S. looks like I'm having the export problem again)

[Figma](https://www.figma.com/file/EQnTidd0B3jyZ8n1c1XBX8CN/twitch?node-id=21%3A3)

<img width="521" alt="Screen Shot 2019-07-04 at 8 13 12 AM" src="https://user-images.githubusercontent.com/30328854/60641241-b2b15e80-9e33-11e9-9182-7e1dc74b63f2.png">

<img width="635" alt="Screen Shot 2019-07-04 at 8 12 37 AM" src="https://user-images.githubusercontent.com/30328854/60641244-b47b2200-9e33-11e9-880b-fc4ccd5d87ba.png">

> Partial icon side-by-side 😄

**Comment by locness3** [comment]
> @locness3 Have updated the logo (P.S. looks like I'm having the export problem again)

Maybe work on spacing at the top-left. Also, why aren't the eyes showing in your side-by-side ?

**Comment by johnletey** [comment]
> Also, why aren't the eyes showing in your side-by-side ?

@locness3 I said that I was having the export problem that I've been having were only some of the icon exports (not all of it) ... this is the sideaffect of putting the partial icon into the side-by-side

**Comment by johnletey** [comment]
> Maybe work on spacing at the top-left. Also, why aren't the eyes showing in your side-by-side ?

Can't really do that ... it's not symetrical anymore if I play with the top-left

**Comment by locness3** [comment]
Ok.

**Comment by johnletey** [comment]
@locness3 So is this okay to submit? @ahtohbi4 what do you think ... any suggestions/comments?

**Comment by ahtohbi4** [comment]
I'd better use a more simplified and schematic version. It seems cleaner and more harmonic among the other icons on my viewpoint.

Native logo from the [Twitch guide](https://www.twitch.tv/p/brand/) is in the red lines:

<img width="452" alt="Снимок экрана 2019-07-05 в 23 22 25" src="https://user-images.githubusercontent.com/3686790/60744142-40e52c00-9f7d-11e9-9534-a17b4d5c344c.png">

<img width="575" alt="Снимок экрана 2019-07-05 в 23 25 03" src="https://user-images.githubusercontent.com/3686790/60744419-7cccc100-9f7e-11e9-9ecf-ae5c43c5972f.png">

**Comment by johnletey** [comment]
@ahtohbi4 I really like that ... it's more simple, but at the same time you can still recognize it as the twitch icon!

**Comment by locness3** [comment]
@johnletey I agree, your current icon is just too cluttered at small sizes. let's go with the one from @ahtohbi4 !

**Comment by johnletey** [comment]
Sounds good @locness3!
