### ISSUE TITLE
Suggested font pairing with icons

### ISSUE THREAD

**Issue by cbw25** [feathericons/feather#592]
Hoping someone can point me in the direction of a few fonts that pair well with this icon set.

Thanks in advance!

**Comment by colebemis** [comment]
@cbw25 [Inter](https://rsms.me/inter/) by @rsms and [Rubik](https://fonts.google.com/specimen/Rubik) are a couple of my favorites. Hope that helps :)

**Comment by colebemis** [comment]
I'm going to go ahead and close this issue. Feel free to reopen it if you have any follow up questions

**Comment by cbw25** [comment]
Helps a ton, thanks so much!

Carter
(832) 542-5365

On May 12, 2019, at 9:36 PM, Cole Bemis <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to go ahead and close this issue. Feel free to reopen it if you have any follow up questions
