### ISSUE TITLE
[file types and more] New set of icons 

### ISSUE THREAD

**Issue by ThomasKuhlmann** [feathericons/feather#593]
I needed a couple of more icons for a project of mine and ended up having 21 new ones created, feel free to include them!

They mostly cover various file types (pdf, zip, charts) with a matching icon to the current file symbol. On top of that there are two new variations for all the new file types and the existing file and file-text icon.

There are also three new icons for presentation and a new counterpart to the link icon (unlink)

![Screen Shot 2019-05-12 at 17 24 32](https://user-images.githubusercontent.com/35376024/57585069-d82c8680-74da-11e9-9003-6b0693f2724c.png)

All the files are saved as svgs here:

https://drive.google.com/open?id=137jtedVGA1MwsxS7ROxYaZyamH7QGN1b

**Comment by locness3** [comment]
Great! Now follow #171

**Comment by locness3** [comment]
@ThomasKuhlmann ...

**Comment by ThomasKuhlmann** [comment]
Created https://github.com/feathericons/feather/pull/596

**Comment by ThomasKuhlmann** [comment]
@locness3 I assume that's what you meant?

**Comment by locness3** [comment]
> @locness3 I assume that's what you meant?

Yes
