### ISSUE TITLE
Icon Request: SoundCloud

### ISSUE THREAD

**Issue by moechaieb** [feathericons/feather#602]
## Icon Request

* Icon name: SoundCloud
* Use case: Musicians who want to link to their SoundCloud from their own website would love this :)
* Screenshots of similar icons: Font Awesome has [a SoundCloud icon](https://fontawesome.com/icons/soundcloud?style=brands). Feather already has a cloud icon, but the contour is very different. Maybe we could just have an alternative cloud icon with a different contour that matches the SoundCloud logo?

![image](https://user-images.githubusercontent.com/4356939/58271582-60701e80-7d5a-11e9-97d0-74f50349e924.png)

**Comment by shawnwwwww** [comment]
#603 idk if i did it correctly 

<img width="626" alt="Screen Shot 2019-05-23 at 11 02 18" src="https://user-images.githubusercontent.com/33641223/58276485-6d861100-7d4c-11e9-9d91-4268d75444c8.png">

**Comment by ahtohbi4** [comment]
If you follow the [Guidelines](https://github.com/feathericons/feather/issues/171#issuecomment-455356985), the icon will be the next:

<img width="439" alt="Снимок экрана 2019-06-28 в 17 51 17" src="https://user-images.githubusercontent.com/3686790/60352769-3bae3d00-99d1-11e9-99b1-04b3c2af07c7.png">

In the set:

<img width="708" alt="Снимок экрана 2019-06-28 в 18 22 54" src="https://user-images.githubusercontent.com/3686790/60353031-cabb5500-99d1-11e9-94a8-c2d6e2377910.png">

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
  <path d="M14 17.9637L18 18C21 17.9637 22 16.5 22 15C22 12 19 12.5 19 12.5C20 9.5 19 7.1 17.5 6.5C16 5.9 14 6.5 14 6.5V17.9637Z"/>
  <path d="M10 8.5V18"/>
  <path d="M6 9.5V17.75"/>
  <path d="M2 13V16.5"/>
</svg>
```

But I'm not sure. :smile:

**Comment by johnletey** [comment]
@ahtohbi4 It's looking really good ... but change the third line to be of the same height as the start of the "cloud" ... this would make it look a lot more like the original icon!

**Comment by locness3** [comment]
> @shawnwwwww if you follow the [Guidelines](https://github.com/feathericons/feather/issues/171#issuecomment-455356985), the icon will be the next:
> 
> <img alt="Снимок экрана 2019-06-28 в 18 35 02" width="481" src="https://user-images.githubusercontent.com/3686790/60353829-8af56d00-99d3-11e9-934c-46bce9774f73.png">
> 
> In the set:
> 
> <img alt="Снимок экрана 2019-06-28 в 18 34 23" width="708" src="https://user-images.githubusercontent.com/3686790/60353850-96e12f00-99d3-11e9-83a4-ad031e2bcdbb.png">
> 
> ```
> <svg
>   xmlns="http://www.w3.org/2000/svg"
>   width="24"
>   height="24"
>   viewBox="0 0 24 24"
>   fill="none"
>   stroke="currentColor"
>   stroke-width="2"
>   stroke-linecap="round"
>   stroke-linejoin="round"
> >
>   <path d="M14 17.9637L18 18C21 17.9637 22 16.5 22 15C22 12.5 19 12.5 19 12.5C20 9.5 19 7.6 17.5 7C16 6.4 14 7 14 7V17.9637Z" />
>   <path d="M10 9V18" />
>   <path d="M6 9V18" />
>   <path d="M2 13V16.5" />
> </svg>
> ```
> 
> But I'm not sure. 😄

Well, go ahead, submit it following #171 !

**Comment by shawnwwwww** [comment]
> @shawnwwwww if you follow the [Guidelines](https://github.com/feathericons/feather/issues/171#issuecomment-455356985), the icon will be the next:
> 
> <img alt="Снимок экрана 2019-06-28 в 18 35 02" width="481" src="https://user-images.githubusercontent.com/3686790/60353829-8af56d00-99d3-11e9-934c-46bce9774f73.png">
> 
> In the set:
> 
> <img alt="Снимок экрана 2019-06-28 в 18 34 23" width="708" src="https://user-images.githubusercontent.com/3686790/60353850-96e12f00-99d3-11e9-83a4-ad031e2bcdbb.png">
> 
> ```
> <svg
>   xmlns="http://www.w3.org/2000/svg"
>   width="24"
>   height="24"
>   viewBox="0 0 24 24"
>   fill="none"
>   stroke="currentColor"
>   stroke-width="2"
>   stroke-linecap="round"
>   stroke-linejoin="round"
> >
>   <path d="M14 17.9637L18 18C21 17.9637 22 16.5 22 15C22 12.5 19 12.5 19 12.5C20 9.5 19 7.6 17.5 7C16 6.4 14 7 14 7V17.9637Z" />
>   <path d="M10 9V18" />
>   <path d="M6 9V18" />
>   <path d="M2 13V16.5" />
> </svg>
> ```
> 
> But I'm not sure. 😄

may i know how did u edit the svg codes to make it cleaner?

**Comment by johnletey** [comment]
@shawnwwwww Clone the repo, add your icon in the `icons/` folder, run `npm install` and then run `npm run build`! That last command formats the icons in a nice and clean manner!

**Comment by ahtohbi4** [comment]
@shawnwwwww The icon above was drawn in Figma, and then its code was cleaned in IDE. The code is already very simple after Figma.

Will you continue your #603?

**Comment by ahtohbi4** [comment]
The second line was lengthened:

<img width="539" alt="Снимок экрана 2019-07-02 в 0 26 11" src="https://user-images.githubusercontent.com/3686790/60467777-33b7fc80-9c60-11e9-8ada-70a8bbbf6322.png">

```svg
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <path d="M14 17.96l4 .04c3-.04 4-1.5 4-3 0-2.5-3-2.5-3-2.5 1-3 0-4.9-1.5-5.5C16 6.4 14 7 14 7v10.96zM10 9v9M6 8v10M2 13v3.5" />
</svg>
```

**Comment by locness3** [comment]
I think that looks kinda weird to be honest

**Comment by ahtohbi4** [comment]
Small update:

<img width="451" alt="Снимок экрана 2019-07-07 в 23 52 13" src="https://user-images.githubusercontent.com/3686790/60773743-6b1c2280-a112-11e9-9555-07baa4cb1241.png">

<img width="365" alt="Снимок экрана 2019-07-07 в 23 53 07" src="https://user-images.githubusercontent.com/3686790/60773745-6eafa980-a112-11e9-84ae-845ed20af189.png">

**Comment by locness3** [comment]
I think you should align the leftmost line at the bottom

**Comment by MarcelloTheArcane** [comment]
See #763

**Comment by locness3** [comment]
> See #763

Guess it's too late

**Comment by moechaieb** [comment]
For reasons outlined in https://github.com/feathericons/feather/issues/763, I'm now going to close this. Thank you to everyone who brought forth ideas and designs :)
