### ISSUE TITLE
Icon Request: Micro.blog

### ISSUE THREAD

**Issue by kaapow** [feathericons/feather#604]
## Icon Request

* Icon name: Micro.blog
* Use case: For all us micro.bloggers
* Screenshots of similar icons:
There is already an ![SVG file available with the logo](https://help.micro.blog/assets/images/icons/web/icon.svg)

And can be found here: [https://help.micro.blog/assets/images/icons/web/icon.svg](https://help.micro.blog/assets/images/icons/web/icon.svg)

**Comment by MarcelloTheArcane** [comment]
![image](https://user-images.githubusercontent.com/21159570/61534049-6ca8ed00-aa26-11e9-94d8-ff10a981119c.png)
![image](https://user-images.githubusercontent.com/21159570/61534037-631f8500-aa26-11e9-9a6d-448aabde7362.png)

**Comment by locness3** [comment]
The star doesn't look that great at small size

**Comment by MarcelloTheArcane** [comment]
I agree. I can resize, or put the stroke on the outside of the star

**Comment by locness3** [comment]
> put the stroke on the outside of the star

That's not allowed in feather

**Comment by MarcelloTheArcane** [comment]
Didn't think so.. I'll make it bigger then

**Comment by kaapow** [comment]
The shape is looking great, but yeah the star will need to get a little bigger.

**Comment by MarcelloTheArcane** [comment]
See #763

**Comment by colebemis** [comment]
Thanks for opening this issue! However, we've decided to stop adding logo icons to Feather (see https://github.com/feathericons/feather/issues/763 for more details).
