### ISSUE TITLE
Icon Request: Campsite

### ISSUE THREAD

**Issue by iamalvisng** [feathericons/feather#61]
Icon name: Campsite
Use case: To describe an outdoor activity
Similar icon: <img width="105" alt="screen shot 2017-06-04 at 9 55 03 am" src="https://cloud.githubusercontent.com/assets/13939164/26758272/ec243022-490b-11e7-8dcd-ab003d6f14bc.png">

**Comment by johnletey** [comment]
@locness3 @colebemis @vizFlux How does [this](https://www.figma.com/file/lhxXpQJUW4aMu0byP6YUJH/campsite) look?

![Screen Shot 2019-07-02 at 7 55 57 AM](https://user-images.githubusercontent.com/30328854/60483617-e3ac5a80-9c9e-11e9-9ec9-e0b76022a707.png)

**Comment by locness3** [comment]
Perfect

**Comment by vizFlux** [comment]
Spot on!

**Comment by johnletey** [comment]
Wonderful ... submitting a PR now!
