### ISSUE TITLE
Icon Request: Undo, Redo/Refresh

### ISSUE THREAD

**Issue by tamb** [feathericons/feather#611]
## Icon Request

* Icon name:  Undo, Redo/Refresh
* Use case: undoing an action, redoing an action or refreshing a feed
* Screenshots of similar icons:
![redo](https://user-images.githubusercontent.com/12103816/58847501-328bb380-8651-11e9-9e2a-8e4be0fd4e61.jpeg)
![60690](https://user-images.githubusercontent.com/12103816/58847503-328bb380-8651-11e9-857c-8c21eba6c2b5.png)

**Comment by colebemis** [comment]
Going to close this issue since we already have #60 👍

**Comment by locness3** [comment]
@colebemis Wait ? Are you back ?!
