### ISSUE TITLE
Icon Request: Wrench / Tool icon

### ISSUE THREAD

**Issue by EssKayz** [feathericons/feather#613]
## Icon Request

* Icon name: Wrench
* Use case: A good icon for stuff like maintenance tasks
* Screenshots of similar icons: 

https://www.iconfinder.com/icons/1074854/configuration_monkey_wrench_settings_spanner_tool_tools_wrench_icon
![image](https://user-images.githubusercontent.com/11611514/58991971-3c005180-87f2-11e9-9685-032e07a73e98.png)

https://icons8.com/icon/24551/wrench
![image](https://user-images.githubusercontent.com/11611514/58991997-46bae680-87f2-11e9-92a9-b8d53ef7373c.png)

**Comment by locness3** [comment]
Screenshot ≠ Link

**Comment by EssKayz** [comment]
Can't paste screenshots from phone. Will update from PC once I get home.

**Comment by Sinequanonh** [comment]
Was just about to request this one 😁

**Comment by ahtohbi4** [comment]
How about this one?

<img width="452" alt="Снимок экрана 2019-07-06 в 17 42 02" src="https://user-images.githubusercontent.com/3686790/60757643-09768e00-a016-11e9-83bc-d953995f66ed.png">

<img width="479" alt="Снимок экрана 2019-07-06 в 17 46 24" src="https://user-images.githubusercontent.com/3686790/60757647-0d0a1500-a016-11e9-8365-e9c4274cf1ae.png">

**Comment by locness3** [comment]
Please rename it to `tool`, and maybe work on "optical volume" (#171). But great!

**Comment by ahtohbi4** [comment]
Maybe something like this?

<img width="451" alt="Снимок экрана 2019-07-07 в 23 33 52" src="https://user-images.githubusercontent.com/3686790/60773569-22fc0080-a110-11e9-8d27-ae2407c30b0d.png">

<img width="366" alt="Снимок экрана 2019-07-07 в 23 33 27" src="https://user-images.githubusercontent.com/3686790/60773570-268f8780-a110-11e9-8b62-df430d8f1032.png">

**Comment by locness3** [comment]
Yes!
