### ISSUE TITLE
Icon Request: Framer

### ISSUE THREAD

**Issue by camacho** [feathericons/feather#614]
## Icon Request

* Icon name: Framer
* Use case: Linking to Framer Cloud files, GitHub actions (or any use of the Framer API), etc
* Screenshots of similar icons:
![Web Mockup](https://user-images.githubusercontent.com/1207450/59024127-8533be00-8851-11e9-8070-478d36f721f3.png)

[framer.svg.zip](https://github.com/feathericons/feather/files/3261021/framer.svg.zip)

The attached SVG icon is 24x24 and a single path that’s been optimized 92% (`d="M12 16v7l-7-7V9h14V2H5l14 14H5"` is all the code it takes)

**Comment by locness3** [comment]
Great! Now follow #171 to adjust to the guidelines and submit your icon.
