### ISSUE TITLE
remove `core-js` from dependencies or upgrade to 3

### ISSUE THREAD

**Issue by iamnewton** [feathericons/feather#618]
## Prerequisites

* Version: 4.22.0
* Are you running from source/master: Import using webpack
* Are you using a released build: yes
* Operating system: MacOS@10.13.6
* Bits: 64 bits

## Step to reproduce

Running storybook to build a component library and everything has been upgraded to `core-js@3`.  Hoping to upgrade here to fix issues elsewhere or remove it from the deps completely and put it in peerDeps.

**Comment by colebemis** [comment]
Just updated `core-js` to `3.1.3`. Let me know if you're able to get it working now.
