### ISSUE TITLE
Add default fill/stroke color

### ISSUE THREAD

**Issue by bdrtsky** [feathericons/feather#674]
This is how icon folder looks in my OS explorer (Ubuntu)

![Screenshot from 2019-07-12 02-29-01](https://user-images.githubusercontent.com/45076741/61091953-e51f1500-a44c-11e9-9c70-b403b11ad74a.png)

Why not to add default fill/stroke color, so humans can preview icons before choosing?

**Comment by bdrtsky** [comment]
This is how **all** other icons packs looks like in Exporer

![Screenshot from 2019-07-12 02-30-45](https://user-images.githubusercontent.com/45076741/61092011-1e578500-a44d-11e9-9495-42cdbcdd92f2.png)

Please consider adding fill color. Or tell how to add it in bulk?

**Comment by johnletey** [comment]
> Why not to add default fill/stroke color, so humans can preview icons before choosing?

I'm confused @bdrtsky ... the guidelines (#171) explicitly say that all icons (if they are to be accepted) have to have a 2px black stroke. So I'm not exactly quite sure what you mean by adding a fill or stroke color, as there is one! Any thoughts @locness3?

**Comment by locness3** [comment]
@johnletey, the stroke color is currentColor in svg file. @bdrtsky asks to replace this color with a "real" color (like black).
But, @bdrtsky, the icons are using currentColor to be simpler to set the color via CSS.
Also your issue might be related to the absence of width and height, and not to the color.

**Comment by locness3** [comment]
What icon pack is the second one BTW @bdrtsky ?

**Comment by bdrtsky** [comment]
@locness3 nope, it's not width and height, it's stroke/fill. 

Screenshot is zwicon pack, if I am not mistaken...

**Comment by locness3** [comment]
> But having no preview for 200 icons makes impossible to even choose the icon.

You can use the website (feathericons.com), and then search in the folder to select the corresponding icon.

**Comment by bdrtsky** [comment]
@locness3 yep, this is the only way right now. Maybe you could make a separate variation folder with fills/strokes, along with `currentColor`?

**Comment by bdrtsky** [comment]
If anyone interested, I fixed it by replacing string with single bash command. 

```
find * -exec sed -i -e 's/stroke="currentColor"/stroke="black"/g' {} \;
```

**Comment by locness3** [comment]
Dn't forget to navigate to your feather folder before running it though.

**Comment by bdrtsky** [comment]
Good point, I edited comment for future reader.
