### ISSUE TITLE
Help-circle missing the dot

### ISSUE THREAD

**Issue by rrsaw** [feathericons/feather#684]
help-circle icon is missing the dot of the question mark :)

**Comment by johnletey** [comment]
@rrsaw I will investigate!

**Comment by locness3** [comment]
Could you tell more ? Where does this happen : on a website, on Figma, on Sketch, ...

**Comment by rrsaw** [comment]
Yes, indeed, sorry for not putting any context from the beginning.
The problem is on Figma release 73 (the latest). When drag-importing the icon help-circle this is the result.

![Screenshot 2019-07-19 at 09 50 56](https://user-images.githubusercontent.com/18010215/61518796-b8e63400-aa0a-11e9-94be-3932829e7ec4.png)

**Comment by rrsaw** [comment]
The Problem seems to be figma-specific. The Icon seems to be working everywhere else.

**Comment by MarcelloTheArcane** [comment]
this might be relevant: https://blog.prototypr.io/how-to-make-a-dot-5ac40102a160

**Comment by locness3** [comment]
Yeah, things said in the article also concern figma.

**Comment by locness3** [comment]
I don't think that the fix is necessary and in compliance with Feather.

**Comment by MarcelloTheArcane** [comment]
Yeah, they render okay in Chrome (which is all I've viewed them in).

@rrsaw If you can find any browsers that don't like it, then it will probably get more important. As it is, you can possibly drag over the whole question mark and play around with stroke - the dot is there, just not visible.
