### ISSUE TITLE
Icon Request: Glitch.com

### ISSUE THREAD

**Issue by CyrilAntoni** [feathericons/feather#743]
* Icon name: Glitch
* Website: https://glitch.com/
* Use case: Social link icon
* Screenshots of similar icons: https://cdn.glitch.com/99defeae-ef08-4bb7-ba01-385a81949100%2Fmask-icon.png?1527766215528

Glitch.com is a website much like CodePen.io or CodeSandbox.io that enables user to create apps directly in the browser.

**Comment by MarcelloTheArcane** [comment]
See #763

**Comment by CyrilAntoni** [comment]
Thanks for the reply!
I didn't know about SimpleIcons. 
It fits my needs perfectly!
