### ISSUE TITLE
Icon Request: Hashtag (#)

### ISSUE THREAD

**Issue by bernaferrari** [feathericons/feather#746]
I think there is room for a hash/hex/hashtag (#) icon, like this: https://materialdesignicons.com/icon/pound. My use case is colors, like #123456.

**Comment by ahtohbi4** [comment]
This one already exists [in the set](https://feathericons.com/?query=hash).

<img width="429" alt="Снимок экрана 2019-09-13 в 11 01 58" src="https://user-images.githubusercontent.com/3686790/64846827-3fd41900-d616-11e9-8a3f-da1dff86186a.png">

**Comment by bernaferrari** [comment]
That feels dumb, I looked twice but couldn't find it. Sorry and thanks!
