### ISSUE TITLE
Icon request: dev.to

### ISSUE THREAD

**Issue by msfjarvis** [feathericons/feather#747]
## Icon Request

* Icon name: dev
* Use case: Social linking to https://dev.to/
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/13348378/64948439-b2eac300-d894-11e9-96d9-3e7baa6dedda.png)

**Comment by MarcelloTheArcane** [comment]
#763

**Comment by msfjarvis** [comment]
That's understandable. Thanks for letting me know!
