### ISSUE TITLE
How to add feather icons to dynamic elements?

### ISSUE THREAD

**Issue by rampatra** [feathericons/feather#758]
I have a code like:
```javascript
var resultsHtml = '';

results.forEach(function(res) {
            resultsHtml += '<li>' +
                '<a class="list-link" href="#">' +
                '<i data-feather="search"></i>' +
                '<span>' + res.title + '</span> in Laptops' +
                '</a>' +
                '</li>';
        });

$('.wrapper').html(resultsHtml);
```

However, the icon isn't being rendered and I think it is because it is added programmatically. When I try to paste the same html code into the .html file, it works fine. Any help here would be great. I saw this: https://github.com/feathericons/feather/issues/447 but are there any other ways?

**Extra Info:**
Feather Icons Version: 4.22.1
OS: macOS High Sierra

**Comment by rampatra** [comment]
Update: I was able to see the icons by calling `feather.replace()` after the above code, however, the icons are not properly sized/aligned. Maybe the css isn't being applied for some reason. Works fine if the elements aren't inserted programmatically.

**Comment by rampatra** [comment]
Was able to solve this by calling ` feather.replace()` after this code. Closing this issue now.

**Comment by locness3** [comment]
Congrats !
