### ISSUE TITLE
Icon request: logo-pinterest

### ISSUE THREAD

**Issue by waatcher** [feathericons/feather#76]
Could you please a new icon?
logo-pinterest

Thanks,
Nick

**Comment by altinselimi** [comment]
Would really appreciate this...

**Comment by leeharding** [comment]
I'll third this — I've needed this a couple of times now... Thanks!

**Comment by MilanovicUros** [comment]
+1 for this please

**Comment by iamkoa** [comment]
+1

**Comment by locness3** [comment]
@dustinlocke ?

**Comment by tpluscode** [comment]
Any chance for this icon?

**Comment by dustinlocke** [comment]
I'll hop on this one!

**Comment by locness3** [comment]
See #763 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tpluscode** [comment]
Thanks for that. I was not aware of simple icons. It is clearly pointless to duplicate the effort
