### ISSUE TITLE
Dev and Social Icons

### ISSUE THREAD

**Issue by sadeghbarati** [feathericons/feather#769]
## Icon Request
https://dribbble.com/shots/2888226-1800-Free-Minimal-Icon-Pack-20x20

pls open link above this will help u 

* Icon name: `wordpress`, `python`, `whatsapp`, `telegram`, `medium`, `dribbble`, `behance`, `trello`, `pintrest`
* Use case:
![Screenshot (9)](https://user-images.githubusercontent.com/17789047/67763311-9e0d5d80-fa04-11e9-8921-b76ab36e657c.png)

* Screenshots of similar icons:

**Comment by johnletey** [comment]
See #763

**Comment by cindehw** [comment]
Upvote for Dribbble!

**Comment by PeterShaggyNoble** [comment]
@cindehw, Dribbble is [available from Simple Icons](https://simpleicons.org/?q=Dribbble).

![Dribbble](https://user-images.githubusercontent.com/15157491/86897069-d8d0a500-c0fe-11ea-858a-dfb3194aa21e.png)

**Comment by locness3** [comment]
@PeterShaggyNoble You should try automate that :joy:

**Comment by PeterShaggyNoble** [comment]
@locness3, I fear that if I could do that then the temptation to spam the issues of every icon library on GitHub might be too much! :laughing:
