### ISSUE TITLE
Icon Request: LinkedIn

### ISSUE THREAD

**Issue by jadchaar** [feathericons/feather#77]
> If you'd like to request an icon, please provide the following information:
> - LinkedIn
> - Social media contact list on website
> - http://fontawesome.io/icon/linkedin/ and http://fontawesome.io/icon/linkedin-square/

**Comment by marinetg** [comment]
+1 vote

**Comment by maraisr** [comment]
+1 vote

**Comment by caiotarifa** [comment]
Maybe something like that:

http://jsbin.com/gafumoqati/edit?html,output

```xml
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin">
  <circle cx="4" cy="5" r="2"></circle>
  <rect x="2" y="10.25" width="4" height="11.75"></rect>
  <path d="M17.3837 10c-1.8723 0-3.1275.9705-3.6414 1.891h-.0515v-1.6H10V22h3.8448v-5.7923c0-1.527.3074-3.0062 2.3097-3.0062 1.9735 0 1.9998 1.7467 1.9998 3.1043V22H22v-6.4224C22 12.4252 21.2806 10 17.3837 10"/>
</svg>
```

**Comment by tobiasmillauer** [comment]
+1

**Comment by lpan** [comment]
+100000000000000

**Comment by NaseebullahSafi** [comment]
It would be a bonus for linkedin icon.

**Comment by maraisr** [comment]
Can't someone just fork this repo, add the icon and just start using the fork! I mean movement on this doesn't seem to be happening....

**Comment by colebemis** [comment]
Feather now has a `linkedin` icon 🎉 Thanks @okcoker!
