### ISSUE TITLE
Icon Request: dev-to

### ISSUE THREAD

**Issue by IsAmrish** [feathericons/feather#775]
## Icon Request

* Icon name: dev-to
* Use case: It will be useful for linking developer profile on https://dev.to
* Screenshots of similar icons:
https://dev.to/

**Comment by johnletey** [comment]
@IsAmrish This is a duplicate of #747.

If your curious as to why it was closed, see #763.

**Comment by colebemis** [comment]
Thanks for opening this issue! But I’m gonna go ahead and close this because of #763
