### ISSUE TITLE
Icons Preview in Mac seems not big

### ISSUE THREAD

**Issue by maverickchangithub** [feathericons/feather#778]
I am so glad i found these beautifully designed icons

But i have one minor request , can you please make the icons preview in Mac look bigger or just stretch fully.

in Windows 10 , after install a svg preview plugin , it's fine. Maybe it is a Mac issue , i don't know. i just want to select icons from finder , not open another browser tab.

Thanks again!

**Comment by locness3** [comment]
Yeah, the problem here is the width and height, because if you don't specify it, macOS makes it the size of a webpage.
