### ISSUE TITLE
Alt text for accessibility

### ISSUE THREAD

**Issue by DawnPaladin** [feathericons/feather#785]
Hello! It would be great if there was a way for me to supply alt text when I include an icon. Something like this:

`<i data-feather="save" data-alt="Save file"></i>`

I'm using the Audit feature of Firefox's awesome new [accessibility inspector](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector) and it's flagging all of my Feather icons. I can use `feather.replace({ alt: '' })` to give all of my icons empty `alt` attributes, but it would be great to be able to specify them individually. Thanks for all of your work on this great library!

**Comment by colebemis** [comment]
Hi, @DawnPaladin! Have you tried this:

```
<i data-feather=“save” alt=“Save file” />

```

All attributes on the `<i>` should be copied to the `<svg>` element.

**Comment by DawnPaladin** [comment]
It works! Amazing! Thank you for your help!
