### ISSUE TITLE
Icon Request: Crunchbase

### ISSUE THREAD

**Issue by josselinlbe** [feathericons/feather#791]
## Icon Request

* Icon name: Crunchbase
* Use case: [Crunchbase](https://www.crunchbase.com/) is the leading destination for company insights from early-stage startups to the Fortune 1000. 
* Screenshots of similar icons: 

![images](https://user-images.githubusercontent.com/15314417/70426212-f0658380-1a72-11ea-8546-2e108cb9391d.png)

**Comment by locness3** [comment]
Your issue doesn't use the issue template, and brand icons in feather have been deprected. See #763

**Comment by josselinlbe** [comment]
Edited.

**Comment by locness3** [comment]
Yeah, but new brand icons won't be added (#763)

**Comment by josselinlbe** [comment]
C'est dommage!
