### ISSUE TITLE
can't render icons dynamically with "-" in name using .toSvg()

### ISSUE THREAD

**Issue by andy-sww** [feathericons/feather#792]
## Prerequisites

* Version: 4.24.1
* Operating system: any

## Step to reproduce
in any .js file:
```javascript 
feather.icons.external-link.toSvg()
```

### Actual behavior
  error (this is obviously inconsitent with JS syntax because of the `-`)

## Any message or error

```javascript
Uncaught ReferenceError: link is not defined
```

## Suggestions

You could use the JS typical approach ommiting the `-` and capitalize every word/string after

```javascript
feather.icons.external-link.toSvg()
``` 
         |
         V
```javascript
feather.icons.externalLink.toSvg()
```

**Comment by locness3** [comment]
Have you tried your suggestion ? Maybe it works already.
And isn't there the possibility to use a string for the icon name ?
BTW, the "JS typical approach" is called **camel case**

**Comment by andy-sww** [comment]
>Have you tried your suggestion ? Maybe it works already.

tried it... doesn't seem to work

>And isn't there the possibility to use a string for the icon name ?

couldn't find it in the docs
also I tried putting a string into a variable and then render the variable using template-strings
```javascript
let myIcon = 'external-link'
feather.icons.`${myIcon}`.toSvg()
```
or something like that ... but than obviously didn't work...
I mean it's not really that important, one could always do
```javascript
exampleNode.innerHTML = '<i data-feather="external-link"></i>'
feather.replace()
```
(but you have to be careful if it's a newly created element that it's already in the DOM before
you call `feather.replace()`)
>BTW, the "JS typical approach" is called camel case

... knew it had a name ;-) thanks

**Comment by colebemis** [comment]
Hi, @andy-sww 😄  Icons with multi-word names (e.g. external-link) cannot be accessed using dot notation (e.g. `feather.icons.x`). Instead, you can use bracket notation (e.g. `feather.icons['external-link'].toSvg()`). There is some documentation on it here: https://github.com/feathericons/feather#feathericons

**Comment by locness3** [comment]
> also I tried putting a string into a variable and then render the variable using template-strings
> 
> ```js
> let myIcon = 'external-link'
> feather.icons.`${myIcon}`.toSvg()
> ```
> 
> or something like that ... but than obviously didn't work...

Yeah, using template strings renders strings, so it wouldn't work in any way.

**Comment by andy-sww** [comment]
> Instead, you can use bracket notation

alright, that makes sence. I'm sorry, I must have overlooked the note in the api reference section.

@colebemis: thank you 😃

**Comment by andy-sww** [comment]
> Instead, you can use bracket notation

alright, that makes sence. I'm sorry, I must have overlooked the note in the api reference section.

@colebemis: thank you 😃
