### ISSUE TITLE
Icon request: Amazon

### ISSUE THREAD

**Issue by MiLeung** [feathericons/feather#795]
## Icon Request

* Icon name: Amazon
* Use case: For Login with Amazon buttons
* Screenshots of similar icons:

![](https://m.media-amazon.com/images/G/01/lwa/btnLWA_drkgry_64x64._CB487588363_.png)
src: https://login.amazon.com/button-guide#website_images

**Comment by locness3** [comment]
Please see #763.

**Comment by MiLeung** [comment]
Thanks. simple-icons will suffice.
