### ISSUE TITLE
Icon Request: Vimeo

### ISSUE THREAD

**Issue by Truefit-Derek** [feathericons/feather#806]
## Icon Request: Vimeo

* Icon name: Vimeo
* Use case: Shows a user has a Vimeo profile, click/tap to go to Vimeo profile.
* Screenshots of similar icons: https://www.google.com/search?q=vimeo+line+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjVkJnQ4fnmAhUIy1kKHW4xA0gQ_AUoAXoECAwQAw&biw=1680&bih=1121

My imperfect version I needed for an app design: ![vimeo](https://user-images.githubusercontent.com/6369943/72180402-1ef9b580-33b5-11ea-8b1d-ba1adad75778.png)

**Comment by lukehol** [comment]
As has already been responded to other pull requests, brand icons have been deprecated. See issue #763.
