### ISSUE TITLE
feather icon in select option

### ISSUE THREAD

**Issue by suatsuphi** [feathericons/feather#828]
Hi
How to show it in select option ?
Could you give a example about that ?

```
<select id="icon">
    <option value="fa fa-address-book">&#xf2b9; address-book</option>
</select>
```

**Comment by locness3** [comment]
Hello! please make your issue more precise. Do you want to add icons to the `option` html element ? If yes, are you using the JS library, inline SVGs, or an icon font or any other method?

**Comment by suatsuphi** [comment]
I've just realized that example was not displayed. For example. 
```
<select id="icon">
    <option value="address-book">&#xf2b9; address-book</option>
</select>
```

**Comment by suatsuphi** [comment]
> Hello! please make your issue more precise. Do you want to add icons to the `option` html element ? If yes, are you using the JS library, inline SVGs, or an icon font or any other method?

I have example for FOntawesome Icon but there is no any example for Father Icon

```
<select id="icon">
    <option value="fa fa-address-book">&#xf2b9; address-book</option>
</select>

```

**Comment by suatsuphi** [comment]
<option   value="icon-activity" > &#xe900;   activity</option>
<option value="icon-airplay"   > &#xe901;     airplay</option>
<option   value="icon-alert-circle" > &#xe902;   alert-circle</option>
<option   value="icon-alert-octagon" > &#xe903;   alert-octagon</option>
<option   value="icon-alert-triangle" > &#xe904;   alert-triangle</option>
<option   value="icon-align-center" > &#xe905;   align-center</option>
<option   value="icon-align-justify" > &#xe906;   align-justify</option>
<option   value="icon-align-left" > &#xe907;   align-left</option>
<option   value="icon-align-right" > &#xe908;   align-right</option>
<option value="icon-anchor"   > &#xe909;     anchor</option>
<option   value="icon-aperture" > &#xe90a;   aperture</option>
<option value="icon-archive"   > &#xe90b;     archive</option>
<option   value="icon-arrow-down-circle" > &#xe90c;   arrow-down-circle</option>
<option   value="icon-arrow-down-left" > &#xe90d;   arrow-down-left</option>
<option   value="icon-arrow-down-right" > &#xe90e;   arrow-down-right</option>
<option   value="icon-arrow-down" > &#xe90f;   arrow-down</option>
<option   value="icon-arrow-left-circle" > &#xe910;   arrow-left-circle</option>
<option   value="icon-arrow-left" > &#xe911;   arrow-left</option>
<option   value="icon-arrow-right-circle" > &#xe912;   arrow-right-circle</option>
<option   value="icon-arrow-right" > &#xe913;   arrow-right</option>
<option   value="icon-arrow-up-circle" > &#xe914;   arrow-up-circle</option>
<option   value="icon-arrow-up-left" > &#xe915;   arrow-up-left</option>
<option   value="icon-arrow-up-right" > &#xe916;   arrow-up-right</option>
<option   value="icon-arrow-up" > &#xe917;   arrow-up</option>
<option value="icon-at-sign"   > &#xe918;     at-sign</option>
<option value="icon-award"   > &#xe919;     award</option>
<option   value="icon-bar-chart-2" > &#xe91a;   bar-chart-2</option>
<option   value="icon-bar-chart" > &#xe91b;   bar-chart</option>
<option   value="icon-battery-charging" > &#xe91c;   battery-charging</option>
<option value="icon-battery"   > &#xe91d;     battery</option>
<option   value="icon-bell-off" > &#xe91e;   bell-off</option>
<option value="icon-bell"   > &#xe91f;   bell</option>
<option   value="icon-bluetooth" > &#xe920;   bluetooth</option>
<option value="icon-bold"   > &#xe921;   bold</option>
<option   value="icon-book-open" > &#xe922;   book-open</option>
<option value="icon-book"   > &#xe923;   book</option>
<option   value="icon-bookmark" > &#xe924;   bookmark</option>
<option value="icon-box"   > &#xe925;   box</option>
<option   value="icon-briefcase" > &#xe926;   briefcase</option>
<option   value="icon-calendar" > &#xe927;   calendar</option>
<option   value="icon-camera-off" > &#xe928;   camera-off</option>
<option value="icon-camera"   > &#xe929;     camera</option>
<option value="icon-cast"   > &#xe92a;   cast</option>
<option   value="icon-check-circle" > &#xe92b;   check-circle</option>
<option   value="icon-check-square" > &#xe92c;   check-square</option>
<option value="icon-check"   > &#xe92d;     check</option>
<option   value="icon-chevron-down" > &#xe92e;   chevron-down</option>
<option   value="icon-chevron-left" > &#xe92f;   chevron-left</option>
<option   value="icon-chevron-right" > &#xe930;   chevron-right</option>
<option   value="icon-chevron-up" > &#xe931;   chevron-up</option>
<option   value="icon-chevrons-down" > &#xe932;   chevrons-down</option>
<option   value="icon-chevrons-left" > &#xe933;   chevrons-left</option>
<option   value="icon-chevrons-right" > &#xe934;   chevrons-right</option>
<option   value="icon-chevrons-up" > &#xe935;   chevrons-up</option>
<option value="icon-chrome"   > &#xe936;     chrome</option>
<option value="icon-circle"   > &#xe937;     circle</option>
<option   value="icon-clipboard" > &#xe938;   clipboard</option>
<option value="icon-clock"   > &#xe939;     clock</option>
<option   value="icon-cloud-drizzle" > &#xe93a;   cloud-drizzle</option>
<option   value="icon-cloud-lightning" > &#xe93b;   cloud-lightning</option>
<option   value="icon-cloud-off" > &#xe93c;   cloud-off</option>
<option   value="icon-cloud-rain" > &#xe93d;   cloud-rain</option>
<option   value="icon-cloud-snow" > &#xe93e;   cloud-snow</option>
<option value="icon-cloud"   > &#xe93f;     cloud</option>
<option value="icon-code"   > &#xe940;   code</option>
<option value="icon-codepen"   > &#xe941;     codepen</option>
<option value="icon-command"   > &#xe942;     command</option>
<option value="icon-compass"   > &#xe943;     compass</option>
<option value="icon-copy"   > &#xe944;   copy</option>
<option   value="icon-corner-down-left" > &#xe945;   corner-down-left</option>
<option   value="icon-corner-down-right" > &#xe946;   corner-down-right</option>
<option   value="icon-corner-left-down" > &#xe947;   corner-left-down</option>
<option   value="icon-corner-left-up" > &#xe948;   corner-left-up</option>
<option   value="icon-corner-right-down" > &#xe949;   corner-right-down</option>
<option   value="icon-corner-right-up" > &#xe94a;   corner-right-up</option>
<option   value="icon-corner-up-left" > &#xe94b;   corner-up-left</option>
<option   value="icon-corner-up-right" > &#xe94c;   corner-up-right</option>
<option value="icon-cpu"   > &#xe94d;   cpu</option>
<option   value="icon-credit-card" > &#xe94e;   credit-card</option>
<option value="icon-crop"   > &#xe94f;   crop</option>
<option   value="icon-crosshair" > &#xe950;   crosshair</option>
<option   value="icon-database" > &#xe951;   database</option>
<option value="icon-delete"   > &#xe952;     delete</option>
<option value="icon-disc"   > &#xe953;   disc</option>
<option   value="icon-dollar-sign" > &#xe954;   dollar-sign</option>
<option   value="icon-download-cloud" > &#xe955;   download-cloud</option>
<option   value="icon-download" > &#xe956;   download</option>
<option value="icon-droplet"   > &#xe957;     droplet</option>
<option value="icon-edit-2"   > &#xe958;     edit-2</option>
<option value="icon-edit-3"   > &#xe959;     edit-3</option>
<option value="icon-edit"   > &#xe95a;   edit</option>
<option   value="icon-external-link" > &#xe95b;   external-link</option>
<option value="icon-eye-off"   > &#xe95c;     eye-off</option>
<option value="icon-eye"   > &#xe95d;   eye</option>
<option   value="icon-facebook" > &#xe95e;   facebook</option>
<option   value="icon-fast-forward" > &#xe95f;   fast-forward</option>
<option value="icon-feather"   > &#xe960;     feather</option>
<option   value="icon-file-minus" > &#xe961;   file-minus</option>
<option   value="icon-file-plus" > &#xe962;   file-plus</option>
<option   value="icon-file-text" > &#xe963;   file-text</option>
<option value="icon-file"   > &#xe964;   file</option>
<option value="icon-film"   > &#xe965;   film</option>
<option value="icon-filter"   > &#xe966;     filter</option>
<option value="icon-flag"   > &#xe967;   flag</option>
<option   value="icon-folder-minus" > &#xe968;   folder-minus</option>
<option   value="icon-folder-plus" > &#xe969;   folder-plus</option>
<option value="icon-folder"   > &#xe96a;     folder</option>
<option value="icon-gift"   > &#xe96b;   gift</option>
<option   value="icon-git-branch" > &#xe96c;   git-branch</option>
<option   value="icon-git-commit" > &#xe96d;   git-commit</option>
<option   value="icon-git-merge" > &#xe96e;   git-merge</option>
<option   value="icon-git-pull-request" > &#xe96f;   git-pull-request</option>
<option value="icon-github"   > &#xe970;     github</option>
<option value="icon-gitlab"   > &#xe971;     gitlab</option>
<option value="icon-globe"   > &#xe972;     globe</option>
<option value="icon-grid"   > &#xe973;   grid</option>
<option   value="icon-hard-drive" > &#xe974;   hard-drive</option>
<option value="icon-hash"   > &#xe975;   hash</option>
<option   value="icon-headphones" > &#xe976;   headphones</option>
<option value="icon-heart"   > &#xe977;     heart</option>
<option   value="icon-help-circle" > &#xe978;   help-circle</option>
<option value="icon-home"   > &#xe979;   home</option>
<option value="icon-image"   > &#xe97a;     image</option>
<option value="icon-inbox"   > &#xe97b;     inbox</option>
<option value="icon-info"   > &#xe97c;   info</option>
<option   value="icon-instagram" > &#xe97d;   instagram</option>
<option value="icon-italic"   > &#xe97e;     italic</option>
<option value="icon-layers"   > &#xe97f;     layers</option>
<option value="icon-layout"   > &#xe980;     layout</option>
<option   value="icon-life-buoy" > &#xe981;   life-buoy</option>
<option value="icon-link-2"   > &#xe982;     link-2</option>
<option value="icon-link"   > &#xe983;   link</option>
<option   value="icon-linkedin" > &#xe984;   linkedin</option>
<option value="icon-list"   > &#xe985;   list</option>
<option value="icon-loader"   > &#xe986;     loader</option>
<option value="icon-lock"   > &#xe987;   lock</option>
<option value="icon-log-in"   > &#xe988;     log-in</option>
<option value="icon-log-out"   > &#xe989;     log-out</option>
<option value="icon-mail"   > &#xe98a;   mail</option>
<option value="icon-map-pin"   > &#xe98b;     map-pin</option>
<option value="icon-map"   > &#xe98c;   map</option>
<option   value="icon-maximize-2" > &#xe98d;   maximize-2</option>
<option   value="icon-maximize" > &#xe98e;   maximize</option>
<option value="icon-menu"   > &#xe98f;   menu</option>
<option   value="icon-message-circle" > &#xe990;   message-circle</option>
<option   value="icon-message-square" > &#xe991;   message-square</option>
<option value="icon-mic-off"   > &#xe992;     mic-off</option>
<option value="icon-mic"   > &#xe993;   mic</option>
<option   value="icon-minimize-2" > &#xe994;   minimize-2</option>
<option   value="icon-minimize" > &#xe995;   minimize</option>
<option   value="icon-minus-circle" > &#xe996;   minus-circle</option>
<option   value="icon-minus-square" > &#xe997;   minus-square</option>
<option value="icon-minus"   > &#xe998;     minus</option>
<option value="icon-monitor"   > &#xe999;     monitor</option>
<option value="icon-moon"   > &#xe99a;   moon</option>
<option   value="icon-more-horizontal" > &#xe99b;   more-horizontal</option>
<option   value="icon-more-vertical" > &#xe99c;   more-vertical</option>
<option value="icon-move"   > &#xe99d;   move</option>
<option value="icon-music"   > &#xe99e;     music</option>
<option   value="icon-navigation-2" > &#xe99f;   navigation-2</option>
<option   value="icon-navigation" > &#xe9a0;   navigation</option>
<option value="icon-octagon"   > &#xe9a1;     octagon</option>
<option value="icon-package"   > &#xe9a2;     package</option>
<option   value="icon-paperclip" > &#xe9a3;   paperclip</option>
<option   value="icon-pause-circle" > &#xe9a4;   pause-circle</option>
<option value="icon-pause"   > &#xe9a5;     pause</option>
<option value="icon-percent"   > &#xe9a6;     percent</option>
<option   value="icon-phone-call" > &#xe9a7;   phone-call</option>
<option   value="icon-phone-forwarded" > &#xe9a8;   phone-forwarded</option>
<option   value="icon-phone-incoming" > &#xe9a9;   phone-incoming</option>
<option   value="icon-phone-missed" > &#xe9aa;   phone-missed</option>
<option   value="icon-phone-off" > &#xe9ab;   phone-off</option>
<option   value="icon-phone-outgoing" > &#xe9ac;   phone-outgoing</option>
<option value="icon-phone"   > &#xe9ad;     phone</option>
<option   value="icon-pie-chart" > &#xe9ae;   pie-chart</option>
<option   value="icon-play-circle" > &#xe9af;   play-circle</option>
<option value="icon-play"   > &#xe9b0;   play</option>
<option   value="icon-plus-circle" > &#xe9b1;   plus-circle</option>
<option   value="icon-plus-square" > &#xe9b2;   plus-square</option>
<option value="icon-plus"   > &#xe9b3;   plus</option>
<option value="icon-pocket"   > &#xe9b4;     pocket</option>
<option value="icon-power"   > &#xe9b5;     power</option>
<option value="icon-printer"   > &#xe9b6;     printer</option>
<option value="icon-radio"   > &#xe9b7;     radio</option>
<option   value="icon-refresh-ccw" > &#xe9b8;   refresh-ccw</option>
<option   value="icon-refresh-cw" > &#xe9b9;   refresh-cw</option>
<option value="icon-repeat"   > &#xe9ba;     repeat</option>
<option value="icon-rewind"   > &#xe9bb;     rewind</option>
<option   value="icon-rotate-ccw" > &#xe9bc;   rotate-ccw</option>
<option   value="icon-rotate-cw" > &#xe9bd;   rotate-cw</option>
<option value="icon-rss"   > &#xe9be;   rss</option>
<option value="icon-save"   > &#xe9bf;   save</option>
<option   value="icon-scissors" > &#xe9c0;   scissors</option>
<option value="icon-search"   > &#xe9c1;     search</option>
<option value="icon-send"   > &#xe9c2;   send</option>
<option value="icon-server"   > &#xe9c3;     server</option>
<option   value="icon-settings" > &#xe9c4;   settings</option>
<option value="icon-share-2"   > &#xe9c5;     share-2</option>
<option value="icon-share"   > &#xe9c6;     share</option>
<option   value="icon-shield-off" > &#xe9c7;   shield-off</option>
<option value="icon-shield"   > &#xe9c8;     shield</option>
<option   value="icon-shopping-bag" > &#xe9c9;   shopping-bag</option>
<option   value="icon-shopping-cart" > &#xe9ca;   shopping-cart</option>
<option value="icon-shuffle"   > &#xe9cb;     shuffle</option>
<option value="icon-sidebar"   > &#xe9cc;     sidebar</option>
<option   value="icon-skip-back" > &#xe9cd;   skip-back</option>
<option   value="icon-skip-forward" > &#xe9ce;   skip-forward</option>
<option value="icon-slack"   > &#xe9cf;     slack</option>
<option value="icon-slash"   > &#xe9d0;     slash</option>
<option value="icon-sliders"   > &#xe9d1;     sliders</option>
<option   value="icon-smartphone" > &#xe9d2;   smartphone</option>
<option value="icon-speaker"   > &#xe9d3;     speaker</option>
<option value="icon-square"   > &#xe9d4;     square</option>
<option value="icon-star"   > &#xe9d5;   star</option>
<option   value="icon-stop-circle" > &#xe9d6;   stop-circle</option>
<option value="icon-sun"   > &#xe9d7;   sun</option>
<option value="icon-sunrise"   > &#xe9d8;     sunrise</option>
<option value="icon-sunset"   > &#xe9d9;     sunset</option>
<option value="icon-tablet"   > &#xe9da;     tablet</option>
<option value="icon-tag"   > &#xe9db;   tag</option>
<option value="icon-target"   > &#xe9dc;     target</option>
<option   value="icon-terminal" > &#xe9dd;   terminal</option>
<option   value="icon-thermometer" > &#xe9de;   thermometer</option>
<option   value="icon-thumbs-down" > &#xe9df;   thumbs-down</option>
<option   value="icon-thumbs-up" > &#xe9e0;   thumbs-up</option>
<option   value="icon-toggle-left" > &#xe9e1;   toggle-left</option>
<option   value="icon-toggle-right" > &#xe9e2;   toggle-right</option>
<option value="icon-trash-2"   > &#xe9e3;     trash-2</option>
<option value="icon-trash"   > &#xe9e4;     trash</option>
<option   value="icon-trending-down" > &#xe9e5;   trending-down</option>
<option   value="icon-trending-up" > &#xe9e6;   trending-up</option>
<option   value="icon-triangle" > &#xe9e7;   triangle</option>
<option value="icon-truck"   > &#xe9e8;     truck</option>
<option value="icon-tv" >   &#xe9e9;   tv</option>
<option value="icon-twitter"   > &#xe9ea;     twitter</option>
<option value="icon-type"   > &#xe9eb;   type</option>
<option   value="icon-umbrella" > &#xe9ec;   umbrella</option>
<option   value="icon-underline" > &#xe9ed;   underline</option>
<option value="icon-unlock"   > &#xe9ee;     unlock</option>
<option   value="icon-upload-cloud" > &#xe9ef;   upload-cloud</option>
<option value="icon-upload"   > &#xe9f0;     upload</option>
<option   value="icon-user-check" > &#xe9f1;   user-check</option>
<option   value="icon-user-minus" > &#xe9f2;   user-minus</option>
<option   value="icon-user-plus" > &#xe9f3;   user-plus</option>
<option value="icon-user-x"   > &#xe9f4;     user-x</option>
<option value="icon-user"   > &#xe9f5;   user</option>
<option value="icon-users"   > &#xe9f6;     users</option>
<option   value="icon-video-off" > &#xe9f7;   video-off</option>
<option value="icon-video"   > &#xe9f8;     video</option>
<option   value="icon-voicemail" > &#xe9f9;   voicemail</option>
<option   value="icon-volume-1" > &#xe9fa;   volume-1</option>
<option   value="icon-volume-2" > &#xe9fb;   volume-2</option>
<option   value="icon-volume-x" > &#xe9fc;   volume-x</option>
<option value="icon-volume"   > &#xe9fd;     volume</option>
<option value="icon-watch"   > &#xe9fe;     watch</option>
<option   value="icon-wifi-off" > &#xe9ff;   wifi-off</option>
<option value="icon-wifi"   > &#xea00;   wifi</option>
<option value="icon-wind"   > &#xea01;   wind</option>
<option   value="icon-x-circle" > &#xea02;   x-circle</option>
<option   value="icon-x-square" > &#xea03;   x-square</option>
<option value="icon-x" >   &#xea04;   x</option>
<option value="icon-youtube"   > &#xea05;     youtube</option>
<option value="icon-zap-off"   > &#xea06;     zap-off</option>
<option value="icon-zap"   > &#xea07;   zap</option>
<option value="icon-zoom-in"   > &#xea08;     zoom-in</option>
<option   value="icon-zoom-out" > &#xea09;   zoom-out</option>

**Comment by locness3** [comment]
Guess you solved your issue, but what are you using to put the icons on your page? The Javascript library? Inline SVGs ?
