### ISSUE TITLE
Icon Request: Mastodon

### ISSUE THREAD

**Issue by muesli** [feathericons/feather#907]
## Icon Request

* Icon name: mastodon
* Use case: Icon for the federated social network Mastodon
* Screenshots of similar icons:

![image](https://user-images.githubusercontent.com/146378/81043359-62bb8200-8eb2-11ea-91e2-f4dcfa4e85b2.png)

**Comment by jletey** [comment]
@muesli Please look at #763.

**Comment by muesli** [comment]
@jletey Thanks. Even though I used the search here, that didn't pop up :disappointed:

**Comment by jletey** [comment]
@muesli No problem, hope that issue helps :)
