### ISSUE TITLE
Icon Request: Tumblr

### ISSUE THREAD

**Issue by gurgunday** [feathericons/feather#909]
## Icon Request

* Icon name: tumblr
* Use case: Another major social media platform's icon that I can put on my website.
* Screenshots of similar icons:
![Tumblr_Logos_2018 03 06_Android Icon Black](https://user-images.githubusercontent.com/57873259/82120265-840f4e80-978d-11ea-9f56-e71a7e5adea8.png)
![Tumblr_Logos_2018 03 06_Android Icon Blue](https://user-images.githubusercontent.com/57873259/82120293-a6a16780-978d-11ea-9913-96e865211aae.png)
![Tumblr_Logos_2018 03 06_iOS Icon Black](https://user-images.githubusercontent.com/57873259/82120295-a86b2b00-978d-11ea-9b85-4ed441108781.png)
![Tumblr_Logos_2018 03 06_iOS Icon Blue](https://user-images.githubusercontent.com/57873259/82120296-a99c5800-978d-11ea-8186-772323c7422f.png)

**Comment by jletey** [comment]
@gurgunday Please look at #763.

**Comment by gurgunday** [comment]
Oh, I checked for dups but didn’t see that. Thanks for pointing it out...
