### ISSUE TITLE
Kafka icon request

### ISSUE THREAD

**Issue by magmax** [feathericons/feather#915]
## Icon Request

* Icon name: kafka
* Use case: kafka topics
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/584026/82790424-50f34c00-9e6c-11ea-842d-b98264ed9d0d.png)

**Comment by jletey** [comment]
@magmax Please look at #763.

**Comment by magmax** [comment]
Thanks @jletey . It has sense.

Anyways, I was going in asking another one: A generic "Queue" icon. Do you think it is more logical?

**Comment by jletey** [comment]
> Anyways, I was going in asking another one: A generic "Queue" icon. Do you think it is more logical?

@magmax Could you maybe expand on what you mean by "queue". If you want, feel free to open another icon request.
