### ISSUE TITLE
Tengo un error 

### ISSUE THREAD

**Issue by josebastian-web** [feathericons/feather#926]
It gives me this error even though I have this cdn`<script src="https://unpkg.com/feather-icons"></script>`

![Captura](https://user-images.githubusercontent.com/26699699/84422670-5af6a800-abeb-11ea-8721-4cc6b5fa399b.PNG)

I just followed the steps of installing this plugin, but it gives me that error

**Comment by jletey** [comment]
Hey Sebastian 👋 

Unfortunately, I don't speak Spanish, but I still want to try and help you out here 😄

Could you give more context into your code 🙏 Potentially a git repository?

---

> I put the above the above into Google Translate 😅

Hola Sebastián 👋

Desafortunadamente, no hablo español, pero todavía quiero intentar ayudarte aquí 😄

¿Podría dar más contexto a su código? ¿Potencialmente un repositorio git?

**Comment by josebastian-web** [comment]
> Hey Sebastian 👋
> 
> Unfortunately, I don't speak Spanish, but I still want to try and help you out here 😄
> 
> Could you give more context into your code 🙏 Potentially a git repository?
> 
> > I put the above the above into Google Translate 😅
> 
> Hola Sebastián 👋
> 
> Desafortunadamente, no hablo español, pero todavía quiero intentar ayudarte aquí 😄
> 
> ¿Podría dar más contexto a su código? ¿Potencialmente un repositorio git?

**Comment by locness3** [comment]
Did you solve your issue? If yes, how?

**Comment by josebastian-web** [comment]
> Did you solve your issue? If yes, how?

Yhea , it was because of the cdn position. 👯 , thanks for answering
