### ISSUE TITLE
Icon Request: Hacker/Coder

### ISSUE THREAD

**Issue by AryanBeezadhur** [feathericons/feather#928]
#746  Icon Request

* Icon name: Hacker and/or Coder
* Use case: security projects
* Screenshots of similar icons: 
![image](https://user-images.githubusercontent.com/34424160/84522099-ee080e80-accd-11ea-8027-69335f20a5c4.png)
&uarr; icon by Freepik on FlatIcon

**Comment by locness3** [comment]
I'm not sure this kind of icons would look great with Feather, as it is complex.
