### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by resynth1943** [feathericons/feather#948]
Hey! I love your project, and I can say that I've been using it for a lot of my projects.

I also am in awe that everything is FOSS! Compared to Font Awesome, that's really something...

Anyway, I can see that you use Google Analytics on your site.

[To encourage FOSS and privacy,](https://resynth1943.net/articles/why-shouldnt-i-use-google-analytics/) perhaps we could look for an alternative? There's [Plausible](https://plausible.io), and [GoatCounter](https://goatcounter.com), which are both pretty dang cool.

Anyway, hope everyone maintaining this project is alright. 😛 Hopefully somebody gets time to have a think about this.

**Comment by locness3** [comment]
Why did you close? It would still be great to consider moving away from google analytics.
