### ISSUE TITLE
Icon Request: highlight marker brush/pen

### ISSUE THREAD

**Issue by IanDarwin** [feathericons/feather#952]
## Icon Request

* Icon name: highlight marker
* Use case: In  a presentation program, to highlight key words
* Screenshots of similar icons:
![markerpen](https://user-images.githubusercontent.com/4762842/88991447-b588b800-d2ae-11ea-90ef-3c5aefc89a7e.png)

**Comment by locness3** [comment]
Possible duplicate of #227

**Comment by IanDarwin** [comment]
> Possible duplicate of #227

Yes, agreed. #227 didn't have a very clear title so I missed it, sorry.
