### ISSUE TITLE
Website shows old icons

### ISSUE THREAD

**Issue by TheWirv** [feathericons/feather#989]
Hi, [feathericons.com](https://feathericons.com) is showing the icon library of version 4.24.1. Also, connected to that, [React Native Vector Icons](https://github.com/oblador/react-native-vector-icons) recently updated to the current version 4.28, and now my shopping cart icon went from outlined to filled (you can check them out [here](https://oblador.github.io/react-native-vector-icons/)). I suspect that you guys improved the library to support multiple variants of icons, like outlined and filled. But via RNVI I have no option to choose between them. Also I can't really look up the current set of available icons because this library's website is not uptodate (it still shows the outlined shopping cart).

Is there anything I can do in order to get the old shopping cart icon back?

**Comment by TheWirv** [comment]
So, nobody cares about the accuracy of the website, I assume?

**Comment by colebemis** [comment]
Should be up-to-date now 👍  Thanks for your patience.

https://github.com/feathericons/feathericons.com/commit/8d5039565595bf4d8bfe6fee544f04d75359afca

**Comment by TheWirv** [comment]
Hi @colebemis thanks for the update. Still, I am somewhat confused about the other issue that I mentioned: [React Native Vector Icons](https://github.com/oblador/react-native-vector-icons) recently updated to 4.28.0, and ever since then the cart icon is different (see 1st image, check it out [here](https://oblador.github.io/react-native-vector-icons/)). Yet, even now with the update, the website still shows the old icon (see 2nd image).

I just would like to know why this might happen?

![image](https://user-images.githubusercontent.com/4397989/99516045-07546b80-298e-11eb-8a23-ee394ffc40b1.png)
![image](https://user-images.githubusercontent.com/4397989/99516118-1d622c00-298e-11eb-9f95-2d68c0bbfd9e.png)
